/*
 *    COPYRIGHT NOTICE
 *
 *   Copyright 2005 Polaris Software Lab Limited. All rights reserved.
 *
 *   These materials are confidential and proprietary to 
 *    Polaris Software Lab Limited and no part of these materials should
 *    be reproduced, published, transmitted or distributed in any form or
 *    by any means, electronic, mechanical, photocopying, recording or 
 *    otherwise, or stored in any information storage or retrieval system
 *    of any nature nor should the materials be disclosed to third parties
 *    or used in any other manner for which this is not authorized, without
 *    the prior express written authorization of Polaris Software Lab Limited.
 */
/*********************************************************************
 *
 * Module Name         :	Maintenance
 *
 * File Name           :	Intl_ErrorMsg.c
 *
 * Description         :	Contains Error Descriptions for the system.
 *
 *           
 *
 *            Version Control Block
 *
 * Date        Version		Author        Description				RFS No.
 * ---------   --------	 --------------  ------------------		---------
 10/10/2005		1.2	Smita Bhat	New File					HDFCMT_003
 *10/11/2005     1.5          ANIL              NEW FILE           HDFCMT_002,HDFCMT_005,HDFCMT_006
 *16/11/2005     1.7          ANIL      Daily Quotations          HDFCMT_009
 *20/12/2005     1.8          Sonali      Daily Float Rate          HDFCMT_012
                                                Added new error messages
 *03/01/2005	  1.11				Smita Bhat			Instrument Changes	HDFCMT_003
*15/12/2005	1.12         Kouser Begum      Maintain Error Description
*10/01/2006			1.13		Pradeep			New error messages for		HDFCMT_017 
*														Index Fund Master
*30/12/2005     1.14         Kouser Begum      Depository Participant   HDFCMT_010                                                         And Credit Rating Agency     HDFCMT_011  
*02/02/2005     1.15         Kouser Begum      Client Master Error Description HDFCMT_001
*07/02/2006     1.16         Kouser Begum      HDFC - New Requirement   HDFCMT_003
*30/01/2006     1.17		Smita Bhat			Added Error Defn for CA		HDFCCA_009
*06/02/2006     1.18         Kouser Begum      HDFC - New Requirement   HDFCMT_003 
*21/02/2006     1.19         Kouser Begum      New Maintenance          KB_001
 *********************************************************************/












 
#include "Intellect_Error.h"

char*	chr_g_error_messages[APL_NBR_ERRORS]=
{
 "",
 "Maker Same as Checker",
 "Mandatory Data Missing",
 "Record Not Found",
 "Value Cannot Be < 0",
 "Value Should Be > 0",
 "Date Cannot Be < Today's Date",
 "Date Cannot Be > Today's Date",
 "Invalid Date",
 "From Date Cannot Be > To Date ",
 "File Not Found",
 "File Is Empty",
 "File Not In Text Format",
 "Time Cannot Be > Current Time",
 "Nothing To Reset",
 "Entered Date Is A Holiday",
 "Date Cannot Be Empty",
 "Cannot Generate Sequence Number",
 "From Value Cannot Be > To Value",
 "Value Not Found",
 "Valid Values Are 'Y/N/Blank'",
 "Date Cannot Be A Future Date",
 "Record Modified By Another User.Please Requery",
 "Database Error: Cannot Update",
 "Data Integrity Error",
 "Account Not Found",
 "Account Not a Customer",
 "Account Cannot Register",
 "Account Already Marked Deleted",
 "Account Not Authorised",
 "Account Already Frozen",
 "Account Already Closed",
 "Invalid IBBS Account",
 "Account Already Exists",
 "Sub Accounts Exist For Master Account",
 "Input bank Internal Account First",
 "Input bank Brokerage Account First",
 "Base Number Should Be Between 1000 And 899999",
 "Account Registration Number Cannot Be Empty",
 "VTB Account Cannot Be Empty",
 "Clearing House Account Cannot Be Empty",
 "Country Code Cannot Be Empty",
 "Domicile Cannot Be Empty",
 "_______________________",
 "Account Classification Code Cannot Be Empty",
 "Short Name Of Account Cannot Be Empty",
 "Our/Their Cannot Be Empty",
 "Customer/Broker/All Cannot Be Empty",
 "IBBS Account Cannot Be Empty",
 "Account Cannot Be Empty",
 "Master Account Cannot Be Empty",
 "Corporate Name Cannot Be Empty",
 "Client Type Cannot Be Empty",
 "Custody/Brokerage/All Cannot Be Empty",
 "Invalid Message Name",
 "Message Types Can Only Be S/T/C/F",
 "Message Frequency Can Only Be Daily/Monthly",
 "Message Address Cannot Be Empty",
 "Invalid Message Category ",
 "Account Not A Broker",
 "Account Not A Dealer",
 "Account Not A Custody Client",
 "Account Not A Brokerage Client",
 "Account Not A Client of Both Custody And Brokerage",
 "Account Not A Master Account",
 "Account Is A Master Account",
 "Account Already Authorised",
 "Account Not Marked Deleted",
 "Account Not Frozen",
 "Account Not Closed",
 "Orders Exist: Cannot Change To Custody Client",
 "Trades Exist: Cannot Change To Brokerage Client",
 "Account Is Counterparty: Cannot Change to Customer",
 "Trades Exist: Cannot Change To Broker",
 "Orders Exist: Cannot Change To Broker",
 "Positions Exist: Cannot Change To Broker",
 "Entitlements Exist: Cannot Change To Broker",
 "Account Defined In Billing: Cannot Change To Brokerage Client",
 "Between Bill Gen & Delivery: Cannot Change Billable Flag",
 "Account Defined In Billing: Cannot Change Billable Flag",
 "bank Internal Account Cannot Be Deleted",
 "bank Brokerage Account Cannot Be Deleted",
 "VTB Account Cannot Be Deleted",
 "Account Marked Unfrozen",
 "Account Marked For Re-Open",
 "Entitlements Exist: Cannot Delete Account",
 "Defined In Billing: Cannot Delete Account",
 "Trades Exist: Cannot Delete Account",
 "Positions Exist: Cannot Delete Account",
 "Orders Exist: Cannot Delete Account",
 "Account Counterparty In Trades: Cannot Delete",
 "Sub Accounts Exist: Cannot Delete Account",
 "bank Internal Account Cannot Be Closed",
 "bank Brokerage Account Cannot Be Closed",
 "VTB Account Cannot Be Closed",
 "Entitlements Exist: Cannot Close Account",
 "Defined In Billing: Cannot Close Account",
 "Positions Exist: Cannot Close Account",
 "Orders Exist: Cannot Close Account",
 "Trades Exist: Cannot Close Account",
 "Account Counterparty In Trades: Cannot Close",
 "Sub Accounts Exist: Cannot Close Account",
 "bank Internal Account Cannot Be Frozen",
 "bank Brokerage Account Cannot Be Frozen",
 "VTB Account Cannot Be Frozen",
 "Message Type Cannot Be Telex",
 "FX Advice Not Allowed For Account",
 "Spot Trades Not Allowed For Account",
 "Account Broker In Orders.Cannot Close",
 "Account Broker In Orders.Cannot Delete",
 "Instrument Not Found",
 "Instrument Not Authorised",
 "Instrument Already Frozen",
 "Instrument Already Marked Deleted",
 "Not a Registered Instrument",
 "From Instrument Cannot Be Same as To Instrument",
 "Instrument Cannot Be Converted",
 "Orders Exist: Cannot Convert Instrument",
 "Payment Trades Exist: Cannot Convert Instrument",
 "Deliver Trades Exist: Cannot Convert Instrument",
 "Instrument Already Exists",
 "Instrument Already Authorised",
 "Instrument Not Marked Deleted",
 "Instrument Not Frozen",
 "Instrument Not A Mother Instrument",
 "Instrument Is A Mother Instrument",
 "Instrument Description Cannot Be Empty",
 "Nominal Value Should Be > 0",
 "PaidUp Capital Should Be > 0",
 "Threshold Limit Cannot Be < 0",
 "Registered Bearer Indicator Cannot Be Empty",
 "Valid Values Are 'RG' And 'BR'",
 "Type Of Investment Cannot Be Empty",
 "Type Of Instrument Cannot Be Empty",
 "Product Type Cannot Be Empty",
 "ISIN Code Cannot Be Empty",
 "Parent Instrument Cannot Be Empty",
 "New Issue Cannot Be Empty",
 "Company Name Cannot Be Empty",
 "Company Address Cannot Be Empty",
 "Issue Date Cannot Be > Last Pay Date",
 "Issue Date Cannot Be > Maturity Date",
 "Interest Type Cannot Be Empty",
 "Payment Frequency Cannot Be Empty",
 "Interest Calculation Type Cannot Be Empty",
 "Last Pay Date Cannot Be > Maturity Date",
 "Last Pay Date Cannot Be > Next Pay Date",
 "Issue Date Cannot Be > Next Pay Date",
 "Next Pay Date Cannot Be > Maturity Date",
 "ISIN Code Cannot Be < 12 Characters",
 "Invalid Investment Type, Instrument Type Combination",
 "Invalid Instrument Type, Product Type Combination",
 "Parent Instrument Cannot Be Same As Instrument",
 "Instrument Not Under Conversion",
 "Instrument Under Conversion",
 "Trades Exist. Cannot Change To Bearer Instrument",
 "Positions Exist.  Cannot Change To Bearer Instrument",
 "Orders Exist: Cannot Change Classification Code",
 "Events Exist: Cannot Change Classification Code",
 "Payment Trades Exist: Cannot Change Classification Code",
 "Sell Orders Exist: Cannot Change Classification Code",
 "Deliver Trades Exist: Cannot Change Classification Code",
 "Events Exist: Cannot Change Type Of Instrument",
 "Between Bill Gen & Delivery. Cannot Change Product Type Of Instrument",
 "Between Bill Gen & Delivery. Cannot Change Instrument Currency",
 "Events Exist: Cannot Delete Instrument",
 "Child Instruments Exist: Cannot Delete Instrument",
 "Trades Exist: Cannot Delete Instrument",
 "Positions Exist: Cannot Delete Instrument",
 "Events Exist: Cannot Change Issue Date",
 "Events Exist: Cannot Change Nominal Value",
 "Events Exist: Cannot Change Interest Calculation Type",
 "Local Reporting Positions Exist: Cannot Delete Instrument",
 "Instrument Is A Registered Instrument",
 "Instrument Cannot Be Empty",
 "Location Not Found",
 "Location Not Authorised",
 "Location Already Exists",
 "Location Already Marked Deleted",
 "Cannot Delete Location: In Use",
 "Location Already Authorised",
 "Location Not Marked Deleted",
 "Location Code Cannot Be Empty",
 "Currency Already Exists",
 "Cannot Delete Domestic Currency",
 "Cannot Delete USD",
 "Cannot Delete Default Billing Currency",
 "Cannot Delete Currency: In Use",
 "Invalid ISO Currency Code",
 "Currency Not Found",
 "Currency Code Cannot Be Empty",
 "Exchange Rate Already Exists For This Date",
 "Exchange Rate Already Authorised",
 "Exchange Rate Not Found",
 "Exchange Rate Not Authorised",
 "No Accounting Entries To Be Reset",
 "Sector Code Cannot Be Empty",
 "Withholding Tax Rate Already Exists For This Country And Product Type",
 "Withholding Tax Rate Not Found For This Country And Product Type",
 "Withholding Tax Rate Already Marked Deleted",
 "Withholding Tax Rate Already Authorised",
 "Withholding Tax Rate Not Marked Deleted",
 "Withholding Tax Rate Not Authorised",
 "Billing Accounts Already Exist",
 "Input Billing Accounts First",
 "Billing Accounts Already Authorised",
 "Account Not In Local Currency",
 "Order Already Executed",
 "Order Not Executed",
 "Qty Cannot Be > Order Qty",
 "Trade Date Cannot Be < Order Date",
 "Breakdown Qty Cannot Be > Total Qty",
 "Instrument Price Cannot Be > Limit Price",
 "Instrument Price Cannot Be < Limit Price",
 "Calculated Countervalue < 0",
 "Insufficient Cash Balance For Account",
 "Not Enough Cash Balance: Cannot Reset",
 "Order Not Found",
 "Order Already Exists",
 "Order Not Authorised",
 "Order Already Authorised",
 "Order Not Marked Deleted",
 "Order Already Marked Deleted",
 "Order Not Marked Cancelled",
 "Order Already Marked Cancelled",
 "Order Not Cancelled",
 "Order Already Cancelled",
 "Order Not Executed",
 "Order Already Executed",
 "Order Not Fully Executed",
 "Order Already Fully Executed",
 "Order Not Partly Executed",
 "Order Already Partly Executed",
 "Order Not Expired",
 "Order Already Expired",
 "Valid Values Are B/S",
 "Not Enough Positions",
 "Local Reference Number Already Exists",
 "Invalid Position Type",
 "Trade Not Found",
 "Trade Already Exists",
 "Child Trade Already Confirmed: Cannot reset",
 "Settlement Date Cannot Be < Trade Date",
 "Not Enough Positions: Cannot Reset",
 "Trade Not Authorised",
 "Trade Already Authorised",
 "Trade Not Marked Deleted",
 "Trade Already Marked Deleted",
 "Trade Not Confirmed",
 "Trade Already Confirmed",
 "Trade Not Settled",
 "Money Already Settled For The Trade",
 "Instrument Already Settled For The Trade",
 "Instrument Not Settled For The Trade",
 "Money Not Settled For The Trade",
 "Trade Not Partially Confirmed",
 "Trade Partially Confirmed",
 "Receive Ticket Not Printed",
 "Deliver Ticket Not Printed",
 "Temp-Out Ticket Not Printed",
 "Temp-Return Ticket Not Printed",
 "Domestic Counterparty Is Local",
 "Domestic Counterparty Is Foreign",
 "Trade Code Invalid For Instrument",
 "Child Records Exist: Cannot Reset",
 "Local Reference Number Cannot Be Empty",
 "Reference Number Cannot Be Empty",
 "Trade Date Cannot Be Empty",
 "Settlement Date Cannot Be Empty",
 "Invalid Type Of Trade For Instrument",
 "Invalid Type Of Trade For Transaction Type",
 "Invalid LR Type Of Trade For Transaction Type",
 "Invalid LR Type Of Trade For Account",
 "Countervalue Should Be > 1",
 "Trade Already Settled",
 "Counterparty Cannot Be Same As Account",
 "Fail Code Cannot Be Empty",
 "Confirmation Date Cannot Be Empty",
 "Confirmation Date Cannot Be < Trade Date",
 "Difference Amount Greater Than Set Up Limit",
 "Quantity Cannot Be Empty",
 "Quantity Should Be < Original Quantity",
 "Amount Should Be < Original Amount",
 "Verified With Cannot Be Empty",
 "Valid Values Are CF0/CF7/CV0/CV1/CV2/CV3/CV4/CV5/CV6/CV7",
 "Not Enough Value Dated Positions",
 "NDS Date Cannot Be < Final Exec Date",
 "Block Conf Date Cannot Be < Exec To Conf Date",
 "Manifold Not Printed",
 "Date Cannot Be < Transaction Date Of Parent",
 "Quantity Cannot Be > Available Quantity",
 "Instrument Settlement Date Cannot Be Empty",
 "Money Settlement Date Cannot Be Empty",
 "Instrument Settlement Date Cannot Be < CSD",
 "Money Settlement Date Cannot Be < CSD",
 "Instrument Settlement Date Cannot Be < Confirmation Date",
 "Money Settlement Date Cannot Be < Confirmation Date",
 "Total Quantity Cannot Be > Trade Quantity",
 "Quantity Cannot Be > Trade Quantity",
 "Money Settlement Date Cannot Be > Instrument Settlement Date",
 "Money Settlement Date Cannot Be < Instrument Settlement Date",
 "Only RVP & DVP Allowed",
 "Invalid Ticket Type",
 "Classification Code Cannot Be Empty",
 "Classification Code Not Found",
 "Valid Values Are 'RG' And 'BR'",
 "Type Of Investment Not Found",
 "Execution Arena Cannot Be Empty",
 "Execution Arena Not Found",
 "New Issue Code Not Found",
 "Interest Type Not Found",
 "Payment Frequency Not Found",
 "Interest Calculation Type Not Found",
 "Invalid Transaction Type",
 "Invalid Type Of Trade",
 "Invalid Local Reporting Type Of Trade",
 "Invalid Fail Code",
 "Invalid Registration Status",
 "Mandatory Data <Key1> Missing",
 "Last Billing Date cannot be in the future ",
 "Cannot Authorise: User same as Maker",
 "Last Billing Date is mandatory",
 "Next Billing Date is mandatory",
 "Bill Delivery Date is mandatory",
 "Billing Control Parameters already exist",
 "Next Billing Date cannot be <= Last Billing Date",
 "Bill Processing Date cannot be <= Last Billing Date",
 "Bill Processing Date cannot be > Next Billing Date",
 "Bill Delivery Date cannot be < Next Billing Date",
 "Fee Structure already exists",
 "Between bill generation and delivery: Cannot change currency",
 "Service Code should be > 0",
 "Service Code already exists",
 "Service Description cannot be blank",
 "Fee Type should be P or U",
 "Account Type should be M or S",
 "Account is not a self billable account",
 "Charge/Fee Type should be S or T",
 "Invalid Service Code",
 "Fee Type Mismatch",
 "Standard Service cannot be deleted",
 "Fee Structure exists",
 "Service cannot be deleted: 'Other Service' not yet billed",
 "Service cannot be deleted: OS Amount > 0 for the service.",
 "Billing Parameters not defined for the Account.",
 "Under Billing/ Over Billing not allowed for current period",
 "<Key1> Amount should be > 0",
 "Service Quantity should be > 0",
 "Minimum Fee should be > 0",
 "Fee Structure for this slab already exists",
 "Billing Control Parameters not setup",
 "Customer not billable",
 "Bill cannot be printed: Customer entered after bill generation",
 "End Date of Period cannot be in the future",
 "End Date of Period cannot be > Next Billing Date",
 "bank Internal client should be billed/send to self",
 "Bill Delivery not due Today",
 "GPSS File not generated",
 "Accounting Entries not generated",
 "Unauthorised Accounts Exist",
 "Nil Fee should be > 0",
 "Maximum Fee should be > 0",
 "Bill Ledger Data Integrity Error",
 "Billing Accounts not found",
 "Billing Accounts not Authorised",
 "Account cannot be bank Brokerage Account",
 "Customer cannot make Payments",
 "Invalid Payment Account",
 "Payment Account not Authorised",
 "Billing Currency/ Payment Account Currency mismatch",
 "Payment Amount should be  > 0",
 "Service Amount should be > 0",
 "Fee Structure does not exist",
 "OS amount < Max write off amount",
 "Scheduled Fee should be >= 0",
 "Master Account not billable",
 "Account billed to master. Cannot change",
 "Bills not delivered",
 "Charge and Fee Types should not be defined for service",
 "Cannot Resend as Reminder: OS amount <= 0",
 "Account not a Master or Bill to Self Account",
 "Cannot Resend: Unauthorised Accounts exist",
 "Cannot Resend: Unauthorised Payments Accounts exist",
 "Billing Accounts have not been input for Accounting Entries",
 "Bills not generated",
 "Accounting Entries already generated",
 "Total Amount mismatch",
 "Cannot delete client: Sub Account with bill to master exists",
 "Regenerate Bills for Account",
 "Bill Generation not due Today",
 "Market Price of Instrument not present",
 "Cannot Allocate Memory",
 "System Date Not Set",
 "Footnote Does Not Exist.",
 "Ex-chr_date for multiple events can't be the same.",
 "Invalid Arguments to the function",
 "Invalid system code",
 "Event Already Exists",
 "Sequence number limit reached.",
 "Holiday Not Found",
 "Holiday Not Authorised",
 "Holiday Already Exists",
 "Holiday Already Marked Deleted",
 "Holiday Already Authorised",
 "Holiday Not Marked Deleted",
 "NDS Confirmation Not Allowed For Trade",
 "NDS Block Conf. Not Allowed For Trade",
 "LR Trade Type Is Empty",
 "Trade Already NDS Confirmed",
 "Trade Already NDS Block Confirmed",
 "Record Already Exists",
 "Partials Not Allowed",
 "Event Not Found",
 "Event Type Invalid For This Instrument",
 "Event Image Record Already Exists.Cannot update",
 "Resultant Instrument Is Not Of Valid Type",
 "Bond Interest Not Supported For Discounted Bonds", 
 "Event Image Record Not Found",
 "Declaration Date Cannot Be > Today's Date",
 "Past Meeting Date Not Accepted",
 "Meeting Date Cannot Be Before Proxy Date",
 "Record Date Should Not Be Before Declaration Date", 
 "Payment Date Should Not Be Before Declaration Date",
 "Response Date Should Not Be Before Record Date",
 "Expiry Date Should Not Be Before Response Date",
 "Pay Date For Duplicate Events Can't Be The Same",
 "Event Status Invalid For Change", 
 "Event Status Invalid For Delete", 
 "Event Status Invalid For Reverse", 
 "Event Status Invalid For Freeze", 
 "Event Status Invalid For UnFreeze", 
 "Event Already Authorised", 
 "Type Of Instrument Not Found",
 "Discount Flag for Bond Is Not Set",
 "Record Modified Earlier By Different User",
 "Event Is In An Invalid Status",
 "Entitlement Is In An Invalid Status",
 "Event For This Payment Not Found",
 "Entitlementent For This Payment Not Found",
 "Payment Already Exists",
 "Payment Not Found",
 "Payment Image Record Already Exists",
 "Payment Status Invalid For Reverse", 
 "Payment Status Invalid For Delete",
 "No Cash Payment Is Due For This Payment", 
 "No Stock Payment Is Due For This Payment", 
 "Payment Date Cannot Be Before Record Date",
 "Sum Of Cash Payments Is Greater Than Entitled Income Due",
 "Sum Of Stock  Payments Is Greater Than Entitled Quantity Due",
 "Cash Payment Cannot Be Greater Than Entitled Income Due", 
 "Stock Payment Cannot Be Greater Than Entitled Quantity Due", 
 "Could Not Register Request To Send Event Reversal Message",
 "Could Not Register Request To Send Entitlement Reversal Message",
 "UnReversed Entitlements Exist.Cannot Reverse", 
 "Unauthorised/UnProcessed Payments Exist.Cannot Reverse", 
 "Valid Values Are EPT/PRO", 
 "CounterParty Clearing A/C Should Be 1-6 Digits", 
 "Weekly Offs Already Input",
 "Cannot Settle Trade 10 Days Before CSD", 
 "Money Settlement Date Cannot Be > System Date + 9", 
 "Cannot Settle Trade Before CSD", 
 "Instrument Settlement Date Cannot Be In Future", 
 "Money Settlement Date Cannot Be In Future", 
 "Instrument Settlement Date Cannot Be < Trade Date", 
 "Money Settlement Date Cannot Be < Trade Date", 
 "Instrument Settlement Date != Money Settlement Date", 
 "Instrument Settlement Date Cannot Be = Money Settlement Date", 
 "Manifold Already Printed", 
 "Parent Record Already Confirmed", 
 "Payment Already Authorised", 
 "Payment Image Record Not Found",
 "Payment Status Invalid For Change",
 "System Generated Trade. Cannot Delete",
 "Trade Reported To Clearing House. Cannot Delete",
 "Confirmed Trade From Order. Cannot Delete", 
 "Unauthorised Weekly Offs Already Exist",
 "Service rendered for this period already exists",
 "Payment Date is mandatory",
 "Payment Date cannot be in the future",
 "Customer not entitled to make payments",
 "Sequence number should be > 0",
 "Payment not found",
 "Payment already authorised",
 "Payment marked for deletion",
 "Trade Date Cannot Be In Future",
 "Trade Date Cannot Be > CSD",
 "Manifold Not Required",
 "Trade Not NDS Block Confirmed",
 "Not Enough Positions. Reset Not Allowed",
 "Transaction In Registration Cycle. Reset Not Allowed",
 "Instrument Converted. Reset Not Allowed",
 "Spot Trade. Reset Not Allowed",
 "Exec. Error Condition <>. Reset Not Allowed",
 "Exec. Error Condition >. Reset Not Allowed",
 "RF/DELV_FREE Trade. Cannot Reset",
 "Registration Qty != Total Qty",
 "Marked Completed Qty != Total Qty",
 "Qty Pending Registration != Total Qty",
 "Partial Settlement Not Allowed For Trade",
 "Cannot Receive Into 000 Position Status",
 "Could not get database context",
 "Withholding Tax Rate Should Be Between 0 And 100",
 "Record Is Not In A Valid Status To Be Reset",
 "Both The Holiday Dates Are The Same",
 "ISIN Code Already Exists",
 "Exec. Error Condition <. Reset Not Allowed",
 "Billing parameters already exist for account",
 "Invalid Commission account",
 "Invalid APA code",
 "Billed to  should be either S or M",
 "Minimum Fee Adjustment should be either Y or N",
 "Min. Fee Adj. in consolidated bill should be 'N' for subaccounts",
 "Master client should be billed to self",
 "Cannot delete client: Fee structure exists",
 "Cannot modify currency:",
 "Charge and Fee basis should not be defined for service",
 "Invalid Combination of Charge/Fee types",
 "Invalid Combination of Charge/Fee basis",
 "Invalid Service dependency",
 "Invalid From Value defined for charge basis",
 "Service Basis should be defined",
 "Fee Slab marked for deletion",
 "Instrument Conversion Is Cyclic",
 "Manifolds Not Allowed For Trade Location",
 "Manifold Already Printed",
 "Manifolds Not Allowed For MinFins",
 "Deliver Trade. Cannot Print Manifolds",
 "Not Enough Quantity For Printing Manifolds",
 "Manifold Quantity != Available Quantity",
 "Nothing To Register",
 "System Generated Trade. Cannot Reset",
 "Deliver Trade. Cannot Reset",
 "Recieve Trade. Cannot Reset",
 "Base number already exists",
 "Total/Service Payment Indicator should be T or S",
 "Purge/Recall chr_flag should be P or R",
 "Service wise Payments not int_found ",
 "Invalid Payment Currency",
 "Message Address not found",
 "Payment already exists",
 "Deletion of total Payment not allowed",
 "Service wise input of Payments not allowed",
 "Valid values for int_first service payment should be Y or N",
 "Deletion of service wise payment not allowed",
 "Record already exists in Ledger",
 "From Location Cannot Be Same As To Location",
 "Nothing To Report",
 "System setup parameters not int_found for billing",
 "No Record in ASECEVT",
 "Send to should be either S or M", 
 "Service Dependency should be defined", 
 "Cannot delete client: Other Service not yet billed", 
 "Cannot delete client: Unauthorised Payments exist", 
 "Cannot delete client: Outstanding Amounts exist", 
 "Between bill generation and delivery: Cannot change billed/send to", 
 "Between bill generation and delivery: Cannot change fees structure", 
 "Between bill generation and delivery: Cannot delete fees structure", 
 "Between bill generation and delivery: Cannot delete account", 
 "Cannot change billing currency: Unauthorised Payments exist", 
 "Invalid From Value defined for Fee basis", 
 "Cannot change billing currency: Outstanding Amounts exist", 
 "Cannot change billing currency: Other Service not yet billed", 
 "Invalid direct debit flag", 
 "Service wise payment already exists",
 "Market Price for the Instrument exists for this date",
 "Market Price Already Authorised",
 "Invalid Data",
 "Instrument Not Undergoing Change",
 "Order Already Executed For Today",
 "Other Service cannot be defined for bank internal account",
 "Other Service already deleted",
 "Other Service already authorised",
 "Other Service marked for deletion",
 "Other Service currency does not match with fees currency setup for account",
 "Feed File Not Valid",
 "Feed File Does Not Contain Today's Prices",
 "Billing client cannot be defined for service",
 "Service Description cannot be changed for standard service",
 "Invalid Fee Type",
 "Other Service not found",
 "Entitlement Status Invalid For Change", 
 "Entitlement Status Invalid For Delete", 
 "Entitlement Status Invalid For Reverse",
 "Entitlement Status Invalid For Freeze",
 "Entitlement Status Invalid For UnFreeze",
 "Entitlement Already Authorised",
 "Record Date has not occured yet",
 "Income Due Cannot be less than Income Received",
 "Quantity Due Cannot be less than Quantity Received",
 "Income Due Is < Income Received + Unprocessed Payments",
 "Quantity Due Is < Quantity Received + Unprocessed Payments",
 "Unreversed Payments exist ,Cannot Reverse",
 "Unreversed OR Unclosed Events exist",
 "UnAuthorised Rights Exist",
 "Unreversed OR Unclosed Events exist, Cannot DELETE",
 "UnAuthorised Rights Exist, Cannot DELETE",
 "Foot Note Already Exists",
 "Entitlement Already Exists",
 "Entitlement Image Already Exists",
 "Event for this entitlement not found",
 "Entitlement not found",
 "Entitlement Image Record Not Found",
 "Record marked for deletion",
 "Record already authorised",
 "Billing Currency/Receivable Account Currency mismatch",
 "Invalid Receivable Account",
 "Fee Slab does not exist",
 "Batch Number not found",
 "Cross Reference Number not int_found for message",
 "Data File for msg not generated",
 "Accounting Entries Hand Off File not generated",
 "Orders Exist: Cannot Delete Instrument",
 "Instruments Exist: Cannot Delete Instrument",
 "Min. Fee Adj. only if holdings exist should be 'Y' or 'N'",
 "Min. Fee Adj. in consolidated bill should be 'Y' or 'N'",
 "Redemption event has already been input for this Instrument",
 "Pay Date cannot be before maturity date",
 "Maturity Date of Instrument has lapsed- cannot input event",
 "Record Date should not be before Ex-Date",
 "Pay Date should not be before Record Date",
 "Record Date should not be before Decl. Date",
 "Ex-Date should not be before Pay Date",
 "Parri Passu Date should not be before Expiry Date",
 "Invalid Mode",
 "Previous Billing Date cannot be modified",
 "Between Bill Gen & Delivery: Cannot Modify Next Billing Date",
 "Between Bill Gen & Delivery: Cannot Modify Bill Proc. Date",
 "Bill Processing Date cannot fall on a holiday",
 "Next Billing Date cannot be in the past",
 "Quantity Cannot Be Less Than Min. FMT Quantity",
 "Remaining Quantity Less Than Min. FMT Quantity",
 "Trade Settled In Past. Cannot Reset",
 "Trade Accounting Entries Already Passed. Cannot Reset",
 "Trade Reported At EOM. Cannot Reset",
 "Statement Message Sent. Cannot Reset",
 "Between Bill Gen And Dlv: Cannot Add/Modify/Delete Service Details",
 "Cannot delete client: Auth. Pymnt(s) not gen./passed for some payments",
 "Depncy. for this service is mandatory for bank Internal Acc.",
 "Fee,Charge Bases for this serv. mandatory for bank Internal Acc.",
 "Cannot process request as EOD has already started",
 "Cannot process request as BOD has not finished",
 "Database Error.Could not write into Audit Log Table",
 "Database Error.Could not get time.Could not chr_log in Audit Table",
 "User is unauthenticated, Access denied",
 "Spot Trade Not Allowed For Free Trade",
 "Effective Date Cannot Be Before Decl Dt",
 "Response Date Is Openended - Response Date Must Be Empty",
 "Expiry Date Is Openended - Expiry Date Must Be Empty",
 "Account Marked Frozen",
 "Global Payments already input for this event",
 "Invalid Event Type for Global Payments",
 "Global Pymts Not Allowed For Rdmp Of Discounted Instr. with tax on mat.",
 "Record is in an invalid status",
 "Pay Date must lie between Rec Dt of event and today",
 "Unauthorised Entitlements exist.Cannot process Global Pymts",
 "Global Payment amount has changed.Please requery for latest values",
 "Global Payment Is Already Deleted Pending Authorise",
 "Global Payment Is Already Authorised. Cannot Delete",
 "Global Payment Record Not Found",
 "Unauthorised Global Payments Exist.Can't Reverse Entitlement",
 "Unauthorised Global Payments Exist.Can't Reverse Event",
 "Message Deleted cannot reset",
 "Base number does not exist",
 "Message not in correct status",
 "Message cannot be generated",
 "Valid chr_value is C",
 "Valid values are B/S/C",
 "Valid values are Y/N",
 "Column should be null",
 "Valid values are T/R/S",
 "Valid values are Y/N/Blank",
 "Valid values are B/S",
 "Valid values are R/P",
 "Valid values are A/R",
 "Value can be from 1 to 999",
 "No event record qualifies for ENRA generation",
 "Unauth Global Pymts Exist.Their Authorisation might be affected",
 "Unauth Global Pymts Exist.Their Authorisation might be affected",
 "Trd. Code, Txn. Type depncy. not allowed for PF Value, No. of Trd.",
 "Dependency for Adm. Fee Should match with Main Service",
 "Dependency for main service not defined",
 "Dependency not defined for service",
 "Invalid Group Value <Key1>",
 "Fee Slabs for RECEIVE_FREE/DELV_FREE not allowed for Txn. Adm. Fee",
 "Multiple Slabs not Allowed for this service",
 "Payment cannot be input manually for Direct Debit Customers",
 "Direct Debit not Allowed for Accounts with Outstanding Amt. > 0",
 "Invalid Dependency - Location Processing not supported",
 "Default Fee Structure Account not set up in Billing",
 "Cyclic Definition for Default Fee Structure Account not allowed",
 "Invalid Default Fee Structure Account",
 "Pay Date Cannot Be After Response Date",
 "Bill Regeneration Not Complete. Please Restart Bill Generation",
 "BOG Code Should Be = 5 Characters",
 "BOG Code Should Be Null For Customers",
 "IBBS Account Should Be = 10 Digits",
 "SAT Account Should Not Be > 11 Digits",
 "SAT Account Should Be Null For Brokers",
 "SAT Code Should Not Be > 11 Digits",
 "SAT Code Should Be Null For Brokers",
 "TYPEOFTRD hould Be Equal To 26", 
 "DOMCPAC Should Be Equal To bank Internal Account",
 "COUNTACC Field Of The First Trade Should Not Be Empty",
 "TRD_STATUS Should Not Be Equal To 'DU' ",
 "Record Already Authorised ",
 "Record Cannot Be Deleted ",
 "Record Cannot Be Authorised ",
 "Sum of Qty Paid > Entitled Posns",
 "Trade Confirmation not Allowed for Dummy Account of EUROCLEAR",
 "Entitlement Input not Allowed for Dummy Account of EUROCLEAR",
 "Invalid Value Of Gross Amount",
 "Account length must be 10",
 "BOG Reference Number Already Exists",
 "DOMCPAC Should Not Be bank Internal Account",
 "TypeOfAccount of Acct and Customer Cannot Be Same",
 "Invalid Location",
 "SAT Account Already Exists",
 "SAT Code Already Exists",
 "Record Date cannot be after the Ex-Date",
 "Pay Date should not be before Ex-Date",
 "Effective Date should be after Record Date",
 "Effective Date cannot be before Ex-Date",
 "Multiple Trades from Order Exec. Found",
 "Cash Account Not Found for Trade Account",
 "Cash Account Should be NULL for trades with Settlement Date < 02/01/2001",
 "Trade Currency Should be EURO Only",
 "Redenomination Events Exist. Reset Not Allowed",
 "Trade Affected By Conversion. Reset Not Allowed",
 "Maintenance for Redenomination Entitlements not allowed",
 "Maintenance for Redenomination Payments not allowed",
 "Specified Currency Not Allowed For Trade",
 "Could not generate CA ref. number",
 "Ibbs client cant have more than one currency",
 "Valid Values Are EPT/PRO/EVI",
 "Valid Values Are EPT/PRO/EVI/VIB",
 "CounterParty Clearing A/C Should Be M00000 Or S00000 ",
 "CounterParty Amount Should Be Greater Than 0.0 ",
 "VTB Account Cannot Begin With Zero",
 "Base Number must be of 6 digits", 
 "'000000' and '999999' are not allowed as Base Number",
 "Synthetic Account is not Valid",
 "Account Type is not Valid",
 "This Customer is marked for Closure",
 "Core Account should be a Non - Proprietary Account",
 "Authorised and Marked for Closure cannot be modified",
 "Not a Valid KCORRESPONDENT Type", 
 "This Location is marked for Closure",  
 "Location Not Closed",
 "Location Already Closed",
 "Product Not Found",
 "Product Not Authorised",
 "Product Already Authorised",
 "State Registration No. Not Found",
 "State Registration No. Not Authorised",
 "State Registration No. Already Authorised",
 "State Registration No. Already Exists",
 "Reference Number Already Exists",
 "Instrument Not Closed",
 "Instrument Already Closed",
 "Synthetic Location is Not Valid",
 "Location Type is not Valid",
 "Product Type is not Valid",
 "Interest Type is not Valid",
 "Days/Date is not Valid",
 "Days/Year is not Valid",
 "Instrument Class is not valid",
 "Instrument Type is not Valid",
 "Not Enough Positions in RUSAFEK", 
 "Input default cash client first",
 "Cannot delete default cash account",
 "One Default CashAccount Is Necessary",
 "Valid Record Not int_found in RRMM  Module",
 "Reset Not Allowed as Instr Converted",
 "Reset Not Allowed for Stock Split Trade",
 "Invalid ISO15022 Location Code",
 "Trade Not Found in RRMM Module",
 "88C/D & 85C/D Should have safekeep_pos SUB A/C ",
 "TradeTo Date Should Not Be Before TradeFrom Date",
 "REPO Block Encountered", 
 "Multiple C-FIAC blocks encountered",
 "Copy of the program is running",
 "Not a valid value",
 "Mismatch of FX inst and type of trade" ,
 "DUMMY Cash Account already present",
 "Assis Code  Already Exists",
 "Assis Code Not Found",
 "Assis Code Already Authorised",
 "Invalid Account Group for the Local Broker",
 "Invalid Account Group for the chr_operator Code",
 "SMI EOD Flag Already Updated for Today",
 "Reset done Once.Cannot Reset Again ",
 "Assis Code Already Deleted",
 "Parent Trade Already Settled",
 "Invalid Trade Status",
 "Txn Adm Fee Currency is allowed only for TxnAdmFee Service",
 "EURO Message Not Sent",
 "Multiple Records Found",
 "Encountered BEFO/AFTE in Linkage Block",
 "From Date cannot be >= Today's Date",
 "Domcp for External trade cannot be a Broker",
 "NTRD Type of Instruments are not Allowed",
 "Deliver Trades Not Allowed for NTRD Type of Instruments",
 "Custodian Cannot Be Same As Account",
 "Function Not Found",
 "Message Function PREA Not Supported",
 "Dir. Debit Payment Generation Day Should be between 1 and 28",
 "Dir. Debit Payment Status Should be U or A",
 "Possible Duplicate Instruction.",
 "Invalid IBAN Account.",
 "Unprocessed Payments Exist : Cannot Modify Event.",
 "Unprocessed Event Modifications Exist.",
 "HDAT Member ID Not Found",
 "HDAT Member ID Already Exists",
 "HDAT Member ID Already Authorised",
 "HDAT Member ID Not Authorised",
 "HDAT Member ID Already Marked Deleted",
 "Not Enough Positions at the Instrument Location",
 "System Date cannot be <= Currency Conversion Date",
 "Trade Date Cannot be older than one year",
 "Settle Date Cannot be older than one year",
 "Settle Date Cannot be later than one year",
 "Product Code Cannot be deleted. Used by Instruments.",
 "Marketable Lot Cannot be Greater Than 1 for Demat Instruments",
 "Instrument Type Is Not Proper",
 "Put Call Details Not Allowed for Instrument",
 "Part Redemption Not Allowed for Instrument",
 "Reset Details Not Allowed for Instrument",
 "PTC Details Not allowed for Instrument",
 "Listing Details Not allowed for Instrument",
 "Redemption Percentage Cannot be Greater than 100",
 "Redemption Value Exceeds Nominal Value of Instrument",
 "Principal and Interest do not match PTC Value",
 "Effective From Date Cannot be Greater Than Effective To Date",
 "Mapping Details Exists for Instrument Cannot Delete",
 "Details Not Found",
 "Details Already Exist",
 "Details Unauthorized",
 "Details Already Authorized",
 "Details Not Marked Delete",
 "Details Already Marked Delete",
 "Details Not Frozen",
 "Details Already Frozen",
 "Key Codes and Key Values MisMatched",
 "PTC Has Been Paid..Cannot Modify PTC Details",
 "Put Call Flag Not Daily; Details Not Accepted",
 "Issue Dt Cant Be > First Pay Dt for Instrument",
 "First Pay Dt Can Be > Maturity Dt for Instrument",
 "Div Rate Not Allowed For Pref Shares",
 "Character Value Not Proper",
 "Company Already Exists",
 "Company Not Found",
 "Company Already Authorised",
 "Company Not Authorised",
 "Company Already Marked Deleted",
 "Company Cannot Be Deleted",
 "Company Cannot Be Modified",
 "Company Cannot Be Reset",
 "Party Already Exists",
 "Cannot Delete Party: In Use",
 "Party Already Marked Deleted",
 "Party Not Found",
 "Party Already Authorised",
 "Party Not Authorised",
 "Invalid PAN Number",
 "Party Bank Details Already Exists",
 "Invalid Bank Account Number",
 "Invalid Main Account Number",
 "Party Bankdetails Already Marked Deleted",
 "Party Exchange Details Already Exists",
 "Party Exchange Details Already Marked Deleted",
 "Party Depository Details Already Exists",
 "Party Depository Details already Marked Deleted",
 "Party Exchange Client Details Exists",
 "Party Exchange Client Details already Marked Deleted",
 "Party Bank Details Not Found",
 "Party Exchange Map Details Not Found",
 "Party Depository Details Not Found",
 "Party Exchange Client Map Details Not Found",
 "Party Bank Details Already Authorised",
 "Party Bank Details Not Authorised",
 "Party Exchange Map Details Already Authorised",
 "Party Exchange Map Details Not Authorised",
 "Party Depository Details Already Authorised",
 "Party Depository Details Not Authorised",
 "Party Exchange Client Map Details Already Authorised",
 "Party Exchange Client Map Details Not Authorised.",
 "Credit Rating Agency Not Found",
 "Credit Rating Agency Already Exists",
 "Credit Rating Agency Not Authorised",
 "Credit Rating Agency Already Authorised",
 "Credit Rating Agency Not Marked Deleted",
 "Credit Rating Agency Already Marked Deleted",
 "Rating Code Not Found",
 "Rating Code Already Exists",
 "Client instrument not found",
 "Client instrument already exists",
 "Client instrument already authorized",
 "Client instrument not authorized",
 "Client instrument marked deleted",
 "Client Instrument record exists",
 "Client instrument can not be deleted.Invalid status",
 "Client instrument can not be authorized.Invalid status",
 "Client instrument can not be reset.Invalid status",
 "Client instrument can not input.Invalid status",
 "Client instrument can not modify.Invalid status",
 "Client instrument can not be modified",
 "Client instrument can not reset",
 "Instruction slip not found",
 "Instruction Slip series from is greater",
 "Instruction slip can not input",
 "Instruction slip can not be modified",
 "Instruction slip can not be authorised",
 "Instruction slip can not be deleted",
 "Instruction slip already exists",
 "Instruction slip is authorised",
 "Instruction slip not authorised",
 "Instruction slip marked deleted",
 "Instruction slip can not reset",
 "Modify not allowed for instruction slip",
 "Reset not allowed for instruction slip ",
 "Settlement calendar not found",
 "Settlement calendar exists",
 "Settlement calendar authorised",
 "Settlement calendar not authorised",
 "Settlement calendar marked deleted",
 "Settlement calendar can not reset",
 "Settlement calendar can not be modified",
 "Daily Quotation not found",
 "Daily Quotation can not input",
 "Daily Quotation can not be modified",
 "Daily Quotation can not be authorised",
 "Daily Quotation can not be deleted",
 "Daily Quotation already exists",
 "Daily Quotation is authorised",
 "Daily Quotation not authorised",
 "Daily Quotation marked deleted",
 "Daily Quotation can not reset",
 "Instrument not authorized",
 "Daily Quotation not marked deleted",
/**939 ERR_PARTY_NOT_MARKED_DEL **/"Party not Marked as deleted",
 /**940 ERR_PTY_BANKDET_NOT_MARKED_DEL**/"Party Bank Details not marked as deleted",
 /**941 ERR_PTY_EXCH_MAP_NOT_MARKED_DEL**/"Party Exchange Details not marked as deleted",
 /**942 ERR_PTY_DEPO_MAP_NOT_MARKED_DEL**/"Party Depository Details not marked as deleted",
 /**943 ERR_PTY_EXCH_CLN_MAP_NOT_MARKED_DEL**/"Party Exchange Client map details not marked as deleted",
 "PTC Value Cannot Exceed Nominal Value of Instrument",
"SEBI Registration Number Already Exists.",
 "RBI Registration Number Already Exists.",
 "Mapinid Already Exists.",  
 "UccCode Already Exists.",
 "SEBI Reg Date Is Greater Than SEBI Reg Exp Date.",
 "RBI Reg Date Is Greater Than RBI Reg Exp Date.",
 "Invalid Master Account Level Creation.",
 "Invalid Signature Passed.",
 "Mapping Details Exist for Client,Cannot Delete",
 "Invalid Master Account Passed.",
 "SEBI Reg Date should not be in Future.", 
 "RBI Reg Date should not be in Future.",
 "Record exists in Instrument Fund Details table",
 "Modification is not allowed",
 "Mapping Depository Participant Details Exist.",
 "Depository Participant Reset cannot be Allowed.",
 "Mapping Credit Rating Details Exist.",
"SEBINo Exists for Other User.",
 "RBINo Exists for Other User.",
 "MapInId Exists for Other User.",
 "UccCode Exists for Other User.",
 "Invalid Instrument Type passed for Exchange Details.",
 "Invalid Instrument Type passed for Redemption Depo Details.",
 "Invalid Instrument Type passed for Redemption Details.",
 "Invalid Instrument Type passed for Credit Rating Details.",
 "Invalid Instrument Type passed for Reset Details.",
 "Invalid Instrument Type passed for PutCall Details.",
 "Invalid Instrument Type passed for PTC Details.",
 "Depo Participant for the Depository Not Found",
 "Depo Participant for the Depository UnAuthorised",
 "Float Rate Instrument for the passed Instrument is Unauthorised.",
 "Invalid Combination of State,City for the Passed Country.",
 "Settlement Calendar Start Date Cannot Be Greater Than End Date.",
 "Settlement Calendar Auction Date Cannot Be Greater Than End Date.",
 "Settlement Calendar NSDL Deadline Date Cannot Be Greater Than End Date.",
 "Settlement Calendar PayIn Date Cannot Be Greater Than NSDL Deadline Date.",
 "Settlement Calendar PayOut Date Cannot Be Greater Than NSDL Deadline Date.",
 "Settlement Calendar PayIn Date Cannot Be Greater Than PayOut Date.",
 "Open Date Cannot be Greater Than Close Date.",
 "Active Date Cannot be Greater Than Close Date.",
 "ClientCode Passed Is Unauthorise Status.",
 "Issue price is less than Face Value",
 "Lower Limit is less then Face Value",
 "Issue Start date greater than end date",
 "Max Quantity is less",
 "Issue Size is less",
 "BCN Not Found", /** BCN Related */
 "BCN Contract Code Should  Start with A .",
 "BCN Already Exists",
 "BCN Already Marked Deleted",
 "Cannot Delete BCN: In Use",
 "BCN Already Authorised",
 "BCN Not Marked Deleted",
 "Modify not possible",
 "Reset is not possible",
 "Authorise not allowed to that status",
 "Override not allowed to that status",
 "Exchange code is not exist in static data",
 "Instrument code is not in authourize status",
 "Client code is not in authourize status",
 "Settlement num is not in authourize status",
 "BCN Details exists in repair Table",
 "Settlement date should be greater than that of Deal date", 
 "Deal date is Holiday",
 "settlement date is holiday",
 "Market type is not exists in static data",
 "Party type is not valid in party master",
 "BCN Already is overrided",
 "BCN Not override",
 "Trans Type not Exists in static data",
 "System Date should be greater than that of Deal Date.", /* ERR_DEALDT_LESSTHAN_SYSDATEA */
 "BCN Qty is More.",
 "BCN DL_Price is not in Band.",
 "Stt Amt is higher Than Specified Limit.", /*** End of BCN **/
 "RECORD ALREADY PRESENT FOR SELECTED DEPOSITORY AND SECURITY",/**TAKEOVER-AMISH**/
 "QUANTITY IS GREATER THEN DEPOSITORY QUANTITY", /****MARKSHORTAGE ****/
 "Exchange code is Invalid. ",/*SQUARE OFF*/
 "Instrument Code is Not Authourized.",
 "Client Code is Not Authourized.",
 "Settlement Number is not Authourized.",/*SQUARE OFF ENDS */
 "ExchOrd Upload instrument code not authorised",
 "ExchOrd Upload client code not authorised",
 "ExchOrd Upload settlment number not authorised",
 "ExchOrd Upload Dealdate is Holiday ",
 "ExchOrd Upload market type is invalid ",
 "ExchOrd Upload Scrip group is invalid ",
 "Deal Information Is missing",
 "Exchange Order Information Is Missing",
 "Exchange Order Not In Proper status ",
 "Deal Not In Proper status ",
 "Bucket Already Exists For Given Deal" ,
 "Address Length Cannot Be Greater Than 11",
 "Deal Date Should be less than End Date",
 "Counter Pty Data Mismatched",
 "Exch Code Is not valid under NSCCL.",
 "Exch Code Is not valid under BOISL.",
 "Brokerage Amount is Higher Than Specified Limit.",
 "Mapping  InterScheme Details Exist",
 "Mapping  Interscheme Child Details Exist",
 "Party Unauthorised",
 "Mapping Block Security Child Details Exists",
 "Instrument code not Authourize .",/* #define ERR_POOLACC_INSTRU_CD_NOT_AUTH 962 */
 "settlement number not Authourised .",/* #define ERR_POOLACC_SETT_NO_NOT_AUTH  964  */
 "Cannot Delete Format: In Use",
 "SEBI Expiry Date is Less Than Deal Date",
 "RBI Expiry Date is Less Than Deal Date",
 "Exch Code is NSE But Contract code had not contain 23.",
 "Exch Code is BSE But Contract code had not contain 01.",
 "Exch Code is NSE But Contract code had not contain 23.",
 "Exch Code is BSE But Contract code had not contain 01.",
 "Client Detail Exist",
 "Application Form Number Exist",
 "Data Mismatch between InterFII and Under Caution Flag .",
 "Not Enough Positions Short Sell Trade Found ",
 "Entitlement for Attached Event not Paid and Closed",
 "PoolAcc Quantity Not Equal to Total Alloted Quantity",
 "Max. Fee Adj. in consolidated bill should be 'Y' or 'N'",
 "Max. Fee Adj. in consolidated bill should be 'N' for subaccounts",
 "Max. Fee Adj. only if holdings exist should be 'Y' or 'N'"
};
