/*
 *    COPYRIGHT NOTICE
 *
 *   Copyright 2005 Polaris Software Lab Limited. All rights reserved.
 *
 *   These materials are confidential and proprietary to 
 *    Polaris Software Lab Limited and no part of these materials should
 *    be reproduced, published, transmitted or distributed in any form or
 *    by any means, electronic, mechanical, photocopying, recording or 
 *    otherwise, or stored in any information storage or retrieval system
 *    of any nature nor should the materials be disclosed to third parties
 *    or used in any other manner for which this is not authorized, without
 *    the prior express written authorization of Polaris Software Lab Limited.
 */
/*********************************************************************
 *
 * Module Name         :	Maintenance
 *
 * File Name           :	Intl_ErrorMsg.c
 *
 * Description         :	Contains Error Descriptions for the system.
 *
 *           
 *
 *            Version Control Block
 *
 * Date        Version		Author        Description				RFS No.
 * ---------   --------	 --------------  ------------------		---------
 10/10/2005		1.2	Smita Bhat	New File					HDFCMT_003
 *10/11/2005     1.5          ANIL              NEW FILE           HDFCMT_002,HDFCMT_005,HDFCMT_006
 *16/11/2005     1.7          ANIL      Daily Quotations          HDFCMT_009
 *20/12/2005     1.8          Sonali      Daily Float Rate          HDFCMT_012
                                                Added new error messages
 *03/01/2005	  1.11				Smita Bhat			Instrument Changes	HDFCMT_003
*15/12/2005	1.12         Kouser Begum      Maintain Error Description
*10/01/2006			1.13		Pradeep			New error messages for		HDFCMT_017 
*														Index Fund Master
*30/12/2005     1.14         Kouser Begum      Depository Participant   HDFCMT_010                                                         And Credit Rating Agency     HDFCMT_011  
*02/02/2005     1.15         Kouser Begum      Client Master Error Description HDFCMT_001
*07/02/2006     1.16         Kouser Begum      HDFC - New Requirement   HDFCMT_003
*30/01/2006     1.17		Smita Bhat			Added Error Defn for CA		HDFCCA_009
*06/02/2006     1.18         Kouser Begum      HDFC - New Requirement   HDFCMT_003 
*21/02/2006     1.19         Kouser Begum      New Maintenance          KB_001
 *********************************************************************/

#include "Intellect_Error.h"

char*	chr_g_error_messages[APL_NBR_ERRORS]=
{
 "",
 "Maker same as Checker",
 "Mandatory data missing",
 "Record not found",
 "Value cannot be < 0",
 "Value should be > 0",
 "Date cannot be < Today's date",
 "Date cannot Be > Today's date",
 "Invalid Date",
 "From Date cannot be > To Date ",
 "File not found",
 "File is empty",
 "File not in text format",
 "Time cannot be > Current Time",
 "Nothing to reset",
 "Entered Date is a holiday",
 "Date cannot be empty",
 "Cannot generate sequence number",
 "From value cannot be > to value",
 "Value not found",
 "Valid values are 'Y/N/Blank'",
 "Date cannot be a future date",
 "Record has been modified. Please check again",
 "Database Error: Cannot update",
 "Data integrity error",
 "Account not found",
 "Account not a customer",
 "Account cannot be registered",
 "Account already marked deleted",
 "Account not authorized",
 "Account already frozen",
 "Account already closed",
 "Invalid IBBS account",
 "Account already exists",
 "Sub-Accounts exist for Master Account",
 "Input bank internal account first",
 "Input bank brokerage account first",
 "Base number should be between 1000 And 899999",
 "Account registration number cannot be empty",
 "VTB Account cannot be empty",
 "Clearing house account cannot be empty",
 "Country Code cannot be empty",
 "Domicile cannot be empty",
 "_______________________",
 "Account classification Code cannot be empty",
 "Short Name of account cannot be empty",
 "Our/Their cannot be empty",
 "Customer/Broker/All cannot be empty",
 "IBBS Account cannot be empty",
 "Account cannot be empty",
 "Master Account cannot be empty",
 "Corporate Name cannot be empty",
 "Client type cannot be empty",
 "Custody/Brokerage/All cannot be empty",
 "Invalid message name",
 "Message types can only be S/T/C/F",
 "Message frequency can only be Daily/Monthly",
 "Message address cannot be empty",
 "Invalid message category ",
 "Account not a broker",
 "Account not a dealer",
 "Account not a custody client",
 "Account not a brokerage client",
 "Account not a client of both custody and brokerage",
 "Account not a master account",
 "Account is a master account",
 "Account already authorized",
 "Account not marked deleted",
 "Account not frozen",
 "Account not closed",
 "Orders Exist: Cannot change to custody client",
 "Trades Exist: Cannot change to brokerage client",
 "Account is counterparty: Cannot change to customer",
 "Trades Exist: Cannot change to broker",
 "Orders Exist: Cannot change To broker",
 "Positions Exist: Cannot change to broker",
 "Entitlements Exist: Cannot change to broker",
 "Account defined in Billing: Cannot change to brokerage client",
 "Between Bill Gen & Delivery: Cannot change billable flag",
 "Account defined in Billing: Cannot change billable flag",
 "Bank's internal account cannot be deleted",
 "Bank's brokerage account cannot be deleted",
 "VTB Account cannot be deleted",
 "Account marked unfrozen",
 "Account marked for Re-Open",
 "Entitlements Exist: Cannot delete account",
 "Defined in Billing: Cannot delete account",
 "Trades Exist: Cannot delete account",
 "Positions Exist: Cannot delete account",
 "Orders Exist: Cannot delete account",
 "Account Counterparty in Trades: Cannot delete",
 "Sub-Accounts Exist: Cannot delete account",
 "Bank's internal account cannot be closed",
 "Bank's brokerage account cannot be closed",
 "VTB Account cannot be closed",
 "Entitlements Exist: Cannot close account",
 "Defined in Billing: Cannot close account",
 "Positions Exist: Cannot close account",
 "Orders Exist: Cannot close account",
 "Trades Exist: Cannot close account",
 "Account Counterparty in Trades: Cannot close",
 "Sub-Accounts Exist: Cannot close account",
 "Bank's internal account cannot be frozen",
 "Bank's brokerage account cannot be frozen",
 "VTB account cannot be frozen",
 "Message type cannot be telex",
 "FX Advice not allowed for account",
 "Spot trades not allowed for account",
 "Account Broker in Orders. Cannot close",
 "Account Broker in Orders. Cannot delete",
 "Instrument not found",
 "Instrument not authorized",
 "Instrument already frozen",
 "Instrument already marked deleted",
 "Not a Registered instrument",
 "From Instrument cannot be same As To Instrument",
 "Instrument cannot be converted",
 "Orders Exist: Cannot convert instrument",
 "Payment Trades Exist: Cannot convert instrument",
 "Deliver Trades Exist: Cannot convert instrument",
 "Instrument already exists",
 "Instrument already authorized",
 "Instrument not marked deleted",
 "Instrument not frozen",
 "Instrument not a mother instrument",
 "Instrument is a mother instrument",
 "Instrument Description cannot be empty",
 "Nominal Value should be > 0",
 "PaidUp capital should be > 0",
 "Threshold limit cannot be < 0",
 "Registered Bearer Indicator Cannot be empty",
 "Valid values are 'RG' and 'BR'",
 "Type of Investment cannot be empty",
 "Type of Instrument cannot be empty",
 "Product Type cannot be empty",
 "ISIN Code cannot be empty",
 "Parent Instrument cannot be empty",
 "New Issue cannot be empty",
 "Company Name cannot be empty",
 "Company Address cannot be empty",
 "Issue Date cannot be > Last Pay Date",
 "Issue Date cannot be > Maturity Date",
 "Interest Type cannot be empty",
 "Payment Frequency cannot be empty",
 "Interest Calculation Type cannot be empty",
 "Last Pay Date cannot be > Maturity Date",
 "Last Pay Date cannot be > Next Pay Date",
 "Issue Date cannot be > Next Pay Date",
 "Next Pay Date cannot be > Maturity Date",
 "ISIN Code cannot be < 12 characters",
 "Invalid Investment Type, Instrument Type combination",
 "Invalid Instrument Type, Product Type combination",
 "Parent Instrument cannot be same as instrument",
 "Instrument not under conversion",
 "Instrument under conversion",
 "Trades Exist. Cannot change to bearer instrument",
 "Positions Exist.  Cannot change to bearer instrument",
 "Orders Exist: Cannot change classification code",
 "Events Exist: Cannot change classification code",
 "Payment Trades Exist: Cannot change classification code",
 "Sell Orders Exist: Cannot change classification code",
 "Deliver Trades Exist: Cannot change classification code",
 "Events Exist: Cannot change type of instrument",
 "Between Bill Gen & Delivery. Cannot change product type of instrument",
 "Between Bill Gen & Delivery. Cannot Change instrument currency",
 "Events Exist: Cannot delete instrument",
 "Child Instruments Exist: Cannot delete instrument",
 "Trades Exist: Cannot delete instrument",
 "Positions Exist: Cannot delete instrument",
 "Events Exist: Cannot change issue date",
 "Events Exist: Cannot change nominal value",
 "Events Exist: Cannot change interest calculation type",
 "Local Reporting Positions Exist: Cannot delete instrument",
 "Instrument is a Registered Instrument",
 "Instrument cannot be empty",
 "Location not found",
 "Location not authorized",
 "Location already exists",
 "Location already marked deleted",
 "Cannot delete location: In use",
 "Location already authorized",
 "Location not marked deleted",
 "Location code cannot be empty",
 "Currency already exists",
 "Cannot delete domestic currency",
 "Cannot delete USD",
 "Cannot delete default billing currency",
 "Cannot delete currency: In use",
 "Invalid ISO currency code",
 "Currency not found",
 "Currency Code cannot be empty",
 "Exchange Rate already exists for this date",
 "Exchange Rate already authorized",
 "Exchange Rate not found",
 "Exchange Rate not authorized",
 "No accounting entries to be reset",
 "Sector Code cannot be empty",
 "Withholding Tax Rate already exists for this country and product type",
 "Withholding Tax Rate not found for this country and product type",
 "Withholding Tax Rate already marked deleted",
 "Withholding Tax Rate already authorized",
 "Withholding Tax Rate not marked deleted",
 "Withholding Tax Rate not authorized",
 "Billing Accounts already exist",
 "Input Billing Accounts first",
 "Billing Accounts already authorized",
 "Account not in local currency",
 "Order already executed",
 "Order not executed",
 "Quantity cannot be > Order Quantity",
 "Trade date cannot be < Order date",
 "Breakdown Quantity cannot be > Total Quantity",
 "Instrument Price cannot be > Limit price",
 "Instrument Price cannot be < Limit price",
 "Calculated countervalue < 0",
 "Insufficient cash balance for account",
 "Not enough cash balance: Cannot reset",
 "Order not found",
 "Order already exists",
 "Order not authorized",
 "Order already authorized",
 "Order not marked deleted",
 "Order already marked deleted",
 "Order not marked cancelled",
 "Order already marked cancelled",
 "Order not cancelled",
 "Order already cancelled",
 "Order not executed",
 "Order already executed",
 "Order not fully executed",
 "Order already fully executed",
 "Order not partly executed",
 "Order already partly executed",
 "Order not expired",
 "Order already expired",
 "Valid values are B/S",
 "Not enough positions",
 "Local reference number already exists",
 "Invalid position type",
 "Trade not found",
 "Trade already exists",
 "Child Trade already confirmed: Cannot reset",
 "Settlement Date cannot be < Trade Date",
 "Not enough positions: Cannot reset",
 "Trade not authorized",
 "Trade already authorized",
 "Trade not marked deleted",
 "Trade already marked deleted",
 "Trade not confirmed",
 "Trade already confirmed",
 "Trade not settled",
 "Money already settled for the trade",
 "Instrument already settled for the trade",
 "Instrument not settled for the trade",
 "Money not settled for the trade",
 "Trade not partially confirmed",
 "Trade partially confirmed",
 "Receive Ticket not printed",
 "Deliver Ticket not printed",
 "Temp-Out Ticket not printed",
 "Temp-Return Ticket not printed",
 "Domestic Counterparty is local",
 "Domestic Counterparty is foreign",
 "Trade Code invalid for instrument",
 "Child records exist: Cannot reset",
 "Local reference number cannot be empty",
 "Reference number cannot be empty",
 "Trade Date cannot be empty",
 "Settlement Date cannot be empty",
 "Invalid Type of Trade for instrument",
 "Invalid Type Of Trade for transaction type",
 "Invalid LR Type of Trade for transaction type",
 "Invalid LR Type of Trade for account",
 "Countervalue should be > 1",
 "Trade already settled",
 "Counterparty cannot be same as account",
 "Fail Code cannot be empty",
 "Confirmation Date cannot be empty",
 "Confirmation Date cannot be < Trade date",
 "Difference Amount greater than set up limit",
 "Quantity cannot be empty",
 "Quantity should be < Original Quantity",
 "Amount should be < Original amount",
 "Verified With cannot be empty",
 "Valid values are CF0/CF7/CV0/CV1/CV2/CV3/CV4/CV5/CV6/CV7",
 "Not enough value dated positions",
 "NDS Date cannot be < Final exec date",
 "Block Conf. Date cannot be < Exec to Conf. Date",
 "Manifold not printed",
 "Date cannot be < Transaction Date of parent",
 "Quantity cannot be > Available Quantity",
 "Instrument Settlement Date cannot be empty",
 "Money Settlement Date cannot be empty",
 "Instrument Settlement Date cannot be < CSD",
 "Money Settlement Date cannot be < CSD",
 "Instrument Settlement Date cannot be < Confirmation Date",
 "Money Settlement Date cannot be < Confirmation Date",
 "Total Quantity cannot be > Trade Quantity",
 "Quantity cannot be > Trade Quantity",
 "Money Settlement Date cannot be > Instrument Settlement Date",
 "Money Settlement Date cannot be < Instrument Settlement Date",
 "Only RVP or DVP allowed",
 "Invalid Ticket Type",
 "Classification Code cannot be empty",
 "Classification Code not found",
 "Valid values are 'RG' and 'BR'",
 "Type Of Investment not found",
 "Execution Arena cannot be empty",
 "Execution Arena not found",
 "New Issue Code not found",
 "Interest Type not found",
 "Payment Frequency not found",
 "Interest Calculation Type not found",
 "Invalid Transaction Type",
 "Invalid Type of Trade",
 "Invalid Local Reporting Type of trade",
 "Invalid Fail Code",
 "Invalid Registration Status",
 "Mandatory Data <Key1> Missing",
 "Last Billing Date cannot be in the future ",
 "Cannot Authorize: User same as Maker",
 "Last Billing Date is mandatory",
 "Next Billing Date is mandatory",
 "Bill Delivery Date is mandatory",
 "Billing Control Parameters already exist",
 "Next Billing Date cannot be <= Last Billing Date",
 "Bill Processing Date cannot be <= Last Billing Date",
 "Bill Processing Date cannot be > Next Billing Date",
 "Bill Delivery Date cannot be < Next Billing Date",
 "Fee Structure already exists",
 "Between bill generation and delivery: Cannot change currency",
 "Service Code should be > 0",
 "Service Code already exists",
 "Service Description cannot be blank",
 "Fee Type should be P or U",
 "Account Type should be M or S",
 "Account is not a self billable account",
 "Charge/Fee Type should be S or T",
 "Invalid Service Code",
 "Fee Type Mismatch",
 "Standard Service cannot be deleted",
 "Fee Structure exists",
 "Service cannot be deleted: 'Other Service' not yet billed",
 "Service cannot be deleted: OS Amount > 0 for the service.",
 "Billing Parameters not defined for the Account.",
 "Under Billing/ Over Billing not allowed for current period",
 "Amount should be > 0",
 "Service Quantity should be > 0",
 "Minimum Fee should be > 0",
 "Fee Structure for this slab already exists",
 "Billing Control Parameters not setup",
 "Customer not billable",
 "Bill cannot be printed: Customer entered after bill generation",
 "End Date of Period cannot be in the future",
 "End Date of Period cannot be > Next Billing Date",
 "Bank's Internal client should be billed/send to self",
 "Bill Delivery not due Today",
 "GPSS File not generated",
 "Accounting Entries not generated",
 "Unauthorized Accounts Exist",
 "Nil Fee should be > 0",
 "Maximum Fee should be > 0",
 "Bill Ledger Data Integrity Error",
 "Billing Accounts not found",
 "Billing Accounts not Authorized",
 "Account cannot be Bank's Brokerage Account",
 "Customer cannot make Payments",
 "Invalid Payment Account",
 "Payment Account not Authorized",
 "Billing Currency/ Payment Account Currency mismatch",
 "Payment Amount should be  > 0",
 "Service Amount should be > 0",
 "Fee Structure does not exist",
 "Outstanding amount < Max write off amount",
 "Scheduled Fee should be > 0",
 "Master Account not billable",
 "Account billed to master. Cannot change",
 "Bills not delivered",
 "Charge and Fee Types should not be defined for service",
 "Cannot resend as reminder: Outstanding amount <= 0",
 "Account not a Master or Bill to Self Account",
 "Cannot Resend: Unauthorized Accounts exist",
 "Cannot Resend: Unauthorized Payments Accounts exist",
 "Billing Accounts have not been input for Accounting Entries",
 "Bills not generated",
 "Accounting Entries already generated",
 "Total Amount mismatch",
 "Cannot delete client: Sub-Account with bill to master exists",
 "Regenerate bills for Account",
 "Bill generation not due Today",
 "Market Price of Instrument not present",
 "Cannot Allocate Memory",
 "System Date Not Set",
 "Footnote does not exist.",
 "Ex-date for multiple events can't be the same.",
 "Invalid Arguments to the function",
 "Invalid system code",
 "Event already exists",
 "Sequence number limit reached.",
 "Holiday not found",
 "Holiday not authorized",
 "Holiday already exists",
 "Holiday already marked deleted",
 "Holiday already authorized",
 "Holiday not marked deleted",
 "NDS Confirmation not allowed for Trade",
 "NDS Block Confirmation not allowed for Trade",
 "LR Trade Type is empty",
 "Trade already NDS confirmed",
 "Trade already NDS Block confirmed",
 "Record already exists",
 "Partials not allowed",
 "Event not found",
 "Event Type invalid for this Instrument",
 "Event Image record already exists.Cannot update",
 "Resultant Instrument is not of valid type",
 "Bond Interest not supported for Discounted Bonds", 
 "Event Image record not found",
 "Declaration Date cannot be > Today's Date",
 "Past Meeting Date not accepted",
 "Meeting Date cannot be before Proxy Date",
 "Record Date should not be before Declaration Date", 
 "Payment Date should not be before Declaration Date",
 "Response Date should not be before Record Date",
 "Expiry Date should not be before Response Date",
 "Pay Date for duplicate events can't be the same",
 "Event Status invalid for change", 
 "Event Status invalid for delete", 
 "Event Status invalid for reverse", 
 "Event Status invalid for freeze", 
 "Event Status invalid for unfreeze", 
 "Event already authorized", 
 "Type of Instrument not found",
 "Discount Flag for Bond is not set",
 "Record modified earlier by different user",
 "Event is in an invalid status",
 "Entitlement is in an invalid status",
 "Event for this Payment not found",
 "Entitlement for this Payment not found",
 "Payment already exists",
 "Payment not found",
 "Payment Image record already exists",
 "Payment Status invalid for reverse", 
 "Payment Status invalid for delete",
 "No cash payment is due for this payment", 
 "No stock payment is due for this payment", 
 "Payment Date cannot be before Record Date",
 "Sum of cash payments is greater than entitled income due",
 "Sum of stock  payments is greater than entitled Quantity due",
 "Cash payment cannot be greater than entitled income due", 
 "Stock payment cannot be greater than entitled Quantity due", 
 "Could not register request to send event reversal message",
 "Could not register request to send entitlement reversal message",
 "UnReversed Entitlements exist.Cannot reverse", 
 "Unauthorized/UnProcessed Payments exist.Cannot reverse", 
 "Valid values are EPT/PRO", 
 "CounterParty Clearing A/C should be 1-6 digits", 
 "Weekly Offs already input",
 "Cannot settle trade 10 Days before CSD", 
 "Money Settlement Date cannot be > System Date + 9", 
 "Cannot settle trade before CSD", 
 "Instrument Settlement Date cannot be in future", 
 "Money Settlement Date cannot be in future", 
 "Instrument Settlement Date cannot be < Trade Date", 
 "Money Settlement Date cannot be < Trade Date", 
 "Instrument Settlement Date not equal to Money Settlement Date", 
 "Instrument Settlement Date cannot be = Money Settlement Date", 
 "Manifold already printed", 
 "Parent record already confirmed", 
 "Payment already authorized", 
 "Payment image record not found",
 "Payment Status invalid for change",
 "System generated trade. Cannot delete",
 "Trade reported to clearing house. Cannot delete",
 "Confirmed Trade generated from given Order. Cannot Delete", 
 "Unauthorized Weekly Offs already exist",
 "Service rendered for this period already exists",
 "Payment Date is mandatory",
 "Payment Date cannot be in the future",
 "Customer not entitled to make payments",
 "Sequence number should be > 0",
 "Payment not found",
 "Payment already authorized",
 "Payment marked for deletion",
 "Trade Date cannot be in future",
 "Trade Date cannot be > CSD",
 "Manifold not required",
 "Trade not NDS Block confirmed",
 "Not enough positions. Reset not allowed",
 "Transaction in Registration cycle. Reset not allowed",
 "Instrument converted. Reset not allowed",
 "Spot Trade. Reset not allowed",
 "Exec. Error Condition '<>'. Reset not allowed",
 "Exec. Error Condition '>'. Reset not allowed",
 "Free of cost trade. Cannot reset",
 "Registration Quantity not equal to Total Quantity",
 "Marked Completed Quantity not equal to Total Quantity",
 "Quantity Pending Registration not equal to Total Quantity",
 "Partial Settlement not allowed for Trade",
 "Cannot receive into 000 position status",
 "Could not get database context",
 "Withholding Tax Rate should be between 0 and 100",
 "Record is not in a valid status to be reset",
 "Both the holiday dates are the same",
 "ISIN Code already exists",
 "Exec. Error Condition '<'. Reset not allowed",
 "Billing parameters already exist for account",
 "Invalid Commission account",
 "Invalid APA code",
 "Billed to  should be either S or M",
 "Minimum Fee Adjustment should be either Y or N",
 "Minimum Fee Adjustment in consolidated bill should be 'N' for subaccounts",
 "Master client should be billed to self",
 "Cannot delete client: Fee structure exists",
 "Cannot modify currency",
 "Charge and Fee basis should not be defined for service",
 "Invalid Combination of Charge/Fee types",
 "Invalid Combination of Charge/Fee basis",
 "Invalid Service dependency",
 "Invalid From Value defined for charge basis",
 "Service Basis should be defined",
 "Fee Slab marked for deletion",
 "Instrument Conversion is cyclic",
 "Manifolds not allowed for Trade Location",
 "Manifold already printed",
 "Manifolds not allowed for MINFINS",
 "Deliver Trade. Cannot print manifolds",
 "Not enough Quantity for printing manifolds",
 "Manifold Quantity not equal to Available Quantity",
 "Nothing to register",
 "System Generated Trade. Cannot reset",
 "Deliver Trade. Cannot reset",
 "Receive Trade. Cannot reset",
 "Base number already exists",
 "Total/Service Payment Indicator should be T or S",
 "Purge/Recall flag should be P or R",
 "Service wise Payments not found ",
 "Invalid Payment Currency",
 "Message Address not found",
 "Payment already exists",
 "Deletion of total Payment not allowed",
 "Service wise input of Payments not allowed",
 "Valid values for first service payment should be Y or N",
 "Deletion of service wise payment not allowed",
 "Record already exists in Ledger",
 "From Location cannot be same as To Location",
 "Nothing to report",
 "System setup parameters not found for billing",
 "No record in CA Setup parameters",
 "Send to should be either S or M", 
 "Service Dependency should be defined", 
 "Cannot delete client: Other Service not yet billed", 
 "Cannot delete client: Unauthorized Payments exist", 
 "Cannot delete client: Outstanding Amounts exist", 
 "Between bill generation and delivery: Cannot change billed/send to", 
 "Between bill generation and delivery: Cannot change fees structure", 
 "Between bill generation and delivery: Cannot delete fees structure", 
 "Between bill generation and delivery: Cannot delete account", 
 "Cannot change billing currency: Unauthorized Payments exist", 
 "Invalid From Value defined for Fee basis", 
 "Cannot change billing currency: Outstanding Amounts exist", 
 "Cannot change billing currency: Other Service not yet billed", 
 "Invalid direct debit flag", 
 "Service wise payment already exists",
 "Market Price for the Instrument exists for this date",
 "Market Price already authorized",
 "Invalid data",
 "Instrument not undergoing change",
 "Order already executed for today",
 "Other Service cannot be defined for bank internal account",
 "Other Service already deleted",
 "Other Service already authorized",
 "Other Service marked for deletion",
 "Other Service currency does not match with fees currency setup for account",
 "Feed file not valid",
 "Feed file does not contain today's prices",
 "Billing client cannot be defined for service",
 "Service Description cannot be changed for standard service",
 "Invalid Fee Type",
 "Other Service not found",
 "Entitlement Status invalid for change", 
 "Entitlement Status invalid for Delete", 
 "Entitlement Status invalid for Reverse",
 "Entitlement Status invalid for Freeze",
 "Entitlement Status invalid for UnFreeze",
 "Entitlement already authorized",
 "Record Date has not occurred yet",
 "Income Due cannot be less than Income Received",
 "Quantity Due cannot be less than Quantity Received",
 "Income Due is < (Income Received + Unprocessed Payments)",
 "Quantity Due is < (Quantity Received + Unprocessed Payments)",
 "Unreversed Payments exist ,Cannot Reverse",
 "Unreversed OR Unclosed Events exist",
 "UnAuthorized Rights Exist",
 "Unreversed OR Unclosed Events exist, Cannot DELETE",
 "UnAuthorized Rights Exist, Cannot DELETE",
 "Foot Note already exists",
 "Entitlement already exists",
 "Entitlement Image already exists",
 "Event for this entitlement not found",
 "Entitlement not found",
 "Entitlement Image record not found",
 "Record marked for deletion",
 "Record already authorized",
 "Billing Currency/Receivable Account Currency mismatch",
 "Invalid Receivable Account",
 "Fee Slab does not exist",
 "Batch Number not found",
 "Cross Reference Number not found for message",
 "Data File for message not generated",
 "Accounting Entries Hand Off File not generated",
 "Orders Exist: Cannot Delete Instrument",
 "Instruments Exist: Cannot Delete Instrument",
 "Minimun Fee Adjustment only if holdings exist should be 'Y' or 'N'",
 "Minimun Fee Adjustment in consolidated bill should be 'Y' or 'N'",
 "Redemption event has already been input for this Instrument",
 "Pay Date cannot be before maturity date",
 "Maturity Date of Instrument has lapsed- cannot input event",
 "Record Date should not be before Ex-Date",
 "Pay Date should not be before Record Date",
 "Record Date should not be before Declaration Date",
 "Ex-Date should not be before Pay Date",
 "Parri Passu Date should not be before Expiry Date",
 "Invalid Mode",
 "Previous Billing Date cannot be modified",
 "Between Bill Generation & Delivery: Cannot modify Next Billing Date",
 "Between Bill Generation & Delivery: Cannot modify Bill Proc. Date",
 "Bill Processing Date cannot fall on a holiday",
 "Next Billing Date cannot be in the past",
 "Quantity cannot be less than min. FMT Quantity",
 "Remaining Quantity less than min. FMT Quantity",
 "Trade Settled in past. Cannot Reset",
 "Trade Accounting Entries already passed. Cannot Reset",
 "Trade Reported at EOM. Cannot Reset",
 "Statement message sent. Cannot Reset",
 "Between Bill Generation And Delivery: Cannot Add/Modify/Delete Service details",
 "Cannot delete client: Authorized Payment(s) not generated/passed for some payments",
 "Dependency for this service is mandatory for bank Internal Account",
 "For this service, Fee and Charge bases mandatory for Bank's Internal Account",
 "Cannot process request as EOD has already started",
 "Cannot process request as BOD has not finished",
 "Database Error.Could not write into Audit Log Table",
 "Database Error.Could not get time.Could not log in Audit Table",
 "User is unauthenticated, Access denied",
 "Spot Trade not allowed for free trade",
 "Effective Date cannot be before Declaration Date",
 "Response Date is Openended - Response Date must be empty",
 "Expiry Date is Openended - Expiry Date must be empty",
 "Account marked Frozen",
 "Global Payments already input for this event",
 "Invalid Event Type for Global Payments",
 "Global Pymts. not allowed for Rdmp. of Discounted Instr. with tax on mat.",
 "Record is in an invalid status",
 "Pay Date must lie between Record Date of event and today",
 "Unauthorized Entitlements exist.Cannot process Global Pymts",
 "Global Payment amount has changed.Please requery for latest values",
 "Global Payment is already deleted pending Authorize",
 "Global Payment is already authorized. Cannot Delete",
 "Global Payment record not found",
 "Unauthorized Global Payments Exist.Can't Reverse Entitlement",
 "Unauthorized Global Payments Exist.Can't Reverse Event",
 "Message Deleted cannot reset",
 "Base number does not exist",
 "Message not in correct status",
 "Message cannot be generated",
 "Valid value is C",
 "Valid values are B/S/C",
 "Valid values are Y/N",
 "Column should be null",
 "Valid values are T/R/S",
 "Valid values are Y/N/Blank",
 "Valid values are B/S",
 "Valid values are R/P",
 "Valid values are A/R",
 "Value can be from 1 to 999",
 "No event record qualifies for ENRA generation",
 "Unauthorized Global Payments Exist.Their Authorization might be affected",
 "Unauthorized Global Payments Exist.Their Authorization might be affected",
 "Trd. Code, Txn. Type depncy. not allowed for PF Value, No. of Trd.",
 "Dependency for Adm. Fee should match with Main Service",
 "Dependency for main service not defined",
 "Dependency not defined for service",
 "Invalid Group value <Key1>",
 "Fee Slabs for FREE Deals not allowed for Transaction Administration Fee",
 "Multiple Slabs not Allowed for this service",
 "Payment cannot be input manually for Direct Debit Customers",
 "Direct Debit not Allowed for Accounts with Outstanding Amt. > 0",
 "Invalid Dependency - Location Processing not supported",
 "Default Fee Structure Account not set up in Billing",
 "Cyclic Definition for Default Fee Structure Account not allowed",
 "Invalid Default Fee Structure Account",
 "Pay Date cannot be after Response Date",
 "Bill Regeneration not complete. Please restart Bill Generation",
 "BOG Code should be = 5 Characters",
 "BOG Code should be Null for Customers",
 "IBBS Account should be = 10 digits",
 "SAT Account should not be > 11 digits",
 "SAT Account should be Null for Brokers",
 "SAT Code should not be > 11 digits",
 "SAT Code should be Null for Brokers",
 "TYPE OF TRADE should be equal to 26", 
 "DOMCPAC should be equal to bank Internal Account",
 "COUNTACC Field of the first trade should not be empty",
 "TRADE STATUS should not be equal to 'DU' ",
 "Record already authorized ",
 "Record cannot be deleted ",
 "Record cannot be authorized ",
 "Sum of Quantity Paid > Entitled Positions",
 "Trade Confirmation not Allowed for Dummy Account of EUROCLEAR",
 "Entitlement Input not Allowed for Dummy Account of EUROCLEAR",
 "Invalid value of Gross Amount",
 "Account length must be 10",
 "BOG Reference Number already exists",
 "DOMCPAC should not be bank Internal Account",
 "Type of Account and Customer cannot be same",
 "Invalid Location",
 "SAT Account already exists",
 "SAT Code already exists",
 "Record Date cannot be after the Ex-Date",
 "Pay Date should not be before Ex-Date",
 "Effective Date should be after Record Date",
 "Effective Date cannot be before Ex-Date",
 "Multiple Trades from Order Exec. found",
 "Cash Account not found for Trade Account",
 "Cash Account should be NULL for trades with Settlement Date < 02/01/2001",
 "Trade Currency should be EURO Only",
 "Redenomination Events exist. Reset not allowed",
 "Trade affected by Conversion. Reset not allowed",
 "Maintenance for Redenomination Entitlements not allowed",
 "Maintenance for Redenomination Payments not allowed",
 "Specified Currency not allowed for Trade",
 "Could not generate CA reference number",
 "Cash Account client can't have more than one currency",
 "Valid values are EPT/PRO/EVI",
 "Valid values are EPT/PRO/EVI/VIB",
 "CounterParty Clearing A/C should be M00000 or S00000 ",
 "CounterParty Amount should be greater than 0.0 ",
 "VTB Account cannot begin with zero",
 "Base Number must be of 6 digits", 
 "'000000' and '999999' are not allowed as Base Number",
 "Synthetic Account is not valid",
 "Account Type is not valid",
 "This Customer is marked for Closure",
 "Core Account should be a Non - Proprietary Account",
 "Authorized and Marked for Closure cannot be modified",
 "Not a Valid KCORRESPONDENT Type", 
 "This Location is marked for Closure",  
 "Location not Closed",
 "Location already Closed",
 "Product not found",
 "Product not Authorized",
 "Product already Authorized",
 "State Registration No. not found",
 "State Registration No. not authorized",
 "State Registration No. already authorized",
 "State Registration No. already exists",
 "Reference Number already exists",
 "Instrument not closed",
 "Instrument already closed",
 "Synthetic Location is not valid",
 "Location Type is not valid",
 "Product Type is not valid",
 "Interest Type is not valid",
 "Days/Date is not valid",
 "Days/Year is not valid",
 "Instrument Class is not valid",
 "Instrument Type is not valid",
 "Not enough positions available", 
 "Input default cash client first",
 "Cannot delete default cash account",
 "One default CashAccount is necessary",
 "Valid record not Found in RRMM  Module",
 "Reset not allowed as Instrument Converted",
 "Reset not allowed for Stock Split Trade",
 "Invalid ISO15022 Location Code",
 "Trade not found in RRMM Module",
 "88C/D & 85C/D should have safekeep position for SUB A/C ",
 "TradeTo Date should not be before TradeFrom Date",
 "REPO Block encountered", 
 "Multiple C-FIAC blocks encountered",
 "Copy of the program is running",
 "Not a valid value",
 "Mismatch of FX instrument and type of trade" ,
 "DUMMY Cash Account already present",
 "Assis Code  already exists",
 "Assis Code not found",
 "Assis Code already authorized",
 "Invalid Account Group for the Local Broker",
 "Invalid Account Group for the operator Code",
 "SMI EOD Flag already Updated for Today",
 "Reset done once.Cannot Reset again ",
 "Assis Code already deleted",
 "Parent Trade already settled",
 "Invalid Trade Status",
 "Txn. Adm. Fee Currency is allowed only for TxnAdmFee Service",
 "EURO Message not sent",
 "Multiple records found",
 "Encountered BEFO/AFTE in Linkage Block",
 "From Date cannot be >= Today's Date",
 "Domestic Counterparty for External trades cannot be a Broker",
 "NTRD Type of Instruments are not allowed",
 "Deliver Trades not allowed for NTRD Type of Instruments",
 "Custodian cannot be same as Account",
 "Function not found",
 "Message Function PREA not supported",
 "Direct Debit Payment Generation Day should be between 1 and 28",
 "Direct Debit Payment Status should be U or A",
 "Possible Duplicate Instruction.",
 "Invalid IBAN Account.",
 "Unprocessed Payments exist : Cannot modify event",
 "Unprocessed Event modifications exist",
 "HDAT Member ID not found",
 "HDAT Member ID already exists",
 "HDAT Member ID already authorized",
 "HDAT Member ID not authorized",
 "HDAT Member ID already marked deleted",
 "Not enough positions at the Instrument Location",
 "System Date cannot be <= Currency Conversion Date",
 "Trade Date Cannot be older than one year",
 "Settlement Date cannot be older than one year",
 "Settlement Date cannot be later than one year",
 "Product Code cannot be deleted. Used by Instruments",
 "Marketable Lot cannot be greater than 1 for Dematerialised Instruments",
 "Instrument Type is not proper",
 "Put Call Details not allowed for Instrument",
 "Part Redemption not allowed for Instrument",
 "Reset Details not allowed for Instrument",
 "PTC Details not allowed for Instrument",
 "Listing Details not allowed for Instrument",
 "Redemption Percentage cannot be greater than 100",
 "Redemption Value exceeds Nominal Value of Instrument",
 "Principal and Interest do not match PTC Value",
 "Effective From Date Cannot be Greater Than Effective To Date",
 "Mapping Details exists for Instrument Cannot Delete",
 "Details not found",
 "Details already exist",
 "Details Unauthorized",
 "Details already Authorized",
 "Details not Marked Delete",
 "Details already Marked Delete",
 "Details not Frozen",
 "Details already Frozen",
 "Key Codes and Key Values MisMatched",
 "PTC has been paid..Cannot modify PTC details",
 "Put Call flag not daily; Details not accepted",
 "Issue Date can't be > First Pay Date for Instrument",
 "First Pay Date can't be > Maturity Date for Instrument",
 "Div Rate not allowed for Preferential Shares",
 "Character value not proper",
 "Company already exists",
 "Company not found",
 "Company already authorized",
 "Company not authorized",
 "Company already marked deleted",
 "Company cannot be deleted",
 "Company cannot be modified",
 "Company cannot be reset",
 "Party already exists",
 "Cannot delete Party: In use",
 "Party already marked deleted",
 "Party not found",
 "Party already authorized",
 "Party not authorized",
 "Invalid PAN number",
 "Party Bank Details already exists",
 "Invalid Bank Account Number",
 "Invalid Main Account Number",
 "Party Bankdetails already marked deleted",
 "Party Exchange Details already exist",
 "Party Exchange Details already marked deleted",
 "Party Depository Details already exist",
 "Party Depository Details already marked deleted",
 "Party Exchange Client Details exist",
 "Party Exchange Client Details already marked deleted",
 "Party Bank Details not found",
 "Party Exchange Map Details not found",
 "Party Depository Details not found",
 "Party Exchange Client Map Details not found",
 "Party Bank Details already authorized",
 "Party Bank Details not authorized",
 "Party Exchange Map Details already authorized",
 "Party Exchange Map Details not authorized",
 "Party Depository Details already authorized",
 "Party Depository Details not authorized",
 "Party Exchange Client Map Details already authorized",
 "Party Exchange Client Map Details not authorized.",
 "Credit Rating Agency not found",
 "Credit Rating Agency already exists",
 "Credit Rating Agency not authorized",
 "Credit Rating Agency already authorized",
 "Credit Rating Agency not marked deleted",
 "Credit Rating Agency already marked deleted",
 "Rating Code not found",
 "Rating Code already exists",
 "Client instrument not found",
 "Client instrument already exists",
 "Client instrument already authorized",
 "Client instrument not authorized",
 "Client instrument marked deleted",
 "Client Instrument record exists",
 "Client instrument can not be deleted.Invalid status",
 "Client instrument can not be authorized.Invalid status",
 "Client instrument can not be reset.Invalid status",
 "Client instrument can not input.Invalid status",
 "Client instrument can not modify.Invalid status",
 "Client instrument can not be modified",
 "Client instrument cannot be reset",
 "Instruction slip not found",
 "Instruction Slip series from is greater",
 "Instruction slip cannot be input",
 "Instruction slip can not be modified",
 "Instruction slip can not be authorized",
 "Instruction slip can not be deleted",
 "Instruction slip already exists",
 "Instruction slip is authorized",
 "Instruction slip not authorized",
 "Instruction slip marked deleted",
 "Instruction slip can not reset",
 "Modify not allowed for instruction slip",
 "Reset not allowed for instruction slip ",
 "Settlement calendar not found",
 "Settlement calendar exists",
 "Settlement calendar authorized",
 "Settlement calendar not authorized",
 "Settlement calendar marked deleted",
 "Settlement calendar cannot be reset",
 "Settlement calendar can not be modified",
 "Daily Quotation not found",
 "Daily Quotation cannot be input",
 "Daily Quotation can not be modified",
 "Daily Quotation can not be authorized",
 "Daily Quotation can not be deleted",
 "Daily Quotation already exists",
 "Daily Quotation is authorized",
 "Daily Quotation not authorized",
 "Daily Quotation marked deleted",
 "Daily Quotation cannot be reset",
 "Instrument not authorized",
 "Daily Quotation not marked deleted",
/**939 ERR_PARTY_NOT_MARKED_DEL **/"Party not marked as deleted",
 /**940 ERR_PTY_BANKDET_NOT_MARKED_DEL**/"Party Bank Details not marked as deleted",
 /**941 ERR_PTY_EXCH_MAP_NOT_MARKED_DEL**/"Party Exchange Details not marked as deleted",
 /**942 ERR_PTY_DEPO_MAP_NOT_MARKED_DEL**/"Party Depository Details not marked as deleted",
 /**943 ERR_PTY_EXCH_CLN_MAP_NOT_MARKED_DEL**/"Party Exchange Client map details not marked as deleted",
 "PTC Value cannot exceed Nominal Value of Instrument",
"SEBI Registration Number already exists",
 "RBI Registration Number already exists",
 "Mapin Id already exists",  
 "UCC Code already exists",
 "SEBI Reg Date is greater than SEBI Reg Expiry Date",
 "RBI Reg Date is greater than RBI Reg Expiry Date",
 "Invalid Master Account level creation",
 "Invalid signature passed",
 "Mapping Details exist for Client,Cannot delete",
 "Invalid Master Account passed",
 "SEBI Reg Date should not be in future", 
 "RBI Reg Date should not be in future",
 "Record exists in Instrument Fund Details table",
 "Modification is not allowed",
 "Mapping Depository Participant details exist",
 "Depository Participant reset cannot be allowed",
 "Mapping Credit Rating details exist",
"SEBINo exists for other user",
 "RBINo exists for other user",
 "Mapin Id exists for other user",
 "UCC Code exists for other user",
 "Invalid Instrument Type passed for Exchange Details",
 "Invalid Instrument Type passed for Redemption Depo Details",
 "Invalid Instrument Type passed for Redemption Details",
 "Invalid Instrument Type passed for Credit Rating Details",
 "Invalid Instrument Type passed for Reset Details",
 "Invalid Instrument Type passed for Put/Call Details",
 "Invalid Instrument Type passed for PTC Details",
 "Depo Participant for the Depository not found",
 "Depo Participant for the Depository unauthorized",
 "Float Rate Instrument for the passed Instrument is unauthorized",
 "Invalid combination of State,City for the passed Country",
 "Settlement Calendar Start Date cannot be greater than End Date",
 "Settlement Calendar Auction Date cannot be greater than End Date",
 "Settlement Calendar NSDL Deadline Date cannot be greater than End Date",
 "Settlement Calendar PayIn Date cannot be greater than NSDL Deadline Date",
 "Settlement Calendar PayOut Date cannot be greater than NSDL Deadline Date",
 "Settlement Calendar PayIn Date cannot be greater than PayOut Date",
 "Open Date cannot be greater than Close Date",
 "Active Date cannot be greater than Close Date",
 "Client Code passed is in unauthorized status",
 "Issue price is less than Face Value",
 "Lower Limit is less then Face Value",
 "Issue Start date greater than end date",
 "Max. Quantity is less",
 "Issue size is less",
 "BCN not found", /** BCN Related */
 "BCN Contract Code should  start with A ",
 "BCN already exists",
 "BCN already marked deleted",
 "Cannot Delete BCN: In use",
 "BCN already authorized",
 "BCN not marked deleted",
 "Modify not possible",
 "Reset is not possible",
 "Authorize not allowed to that status",
 "Override not allowed to that status",
 "Exchange code does not exist in static data",
 "Instrument code is not in authorized status",
 "Client code is not in authorized status",
 "Settlement number is not in authorized status",
 "BCN Details exist in repair Table",
 "Settlement date should be greater than Deal date", 
 "Deal date is Holiday",
 "Settlement date is holiday",
 "Market type does not exist in static data",
 "Party type is not valid in party master",
 "BCN is already overridden",
 "BCN not overridden",
 "Transaction Type does not exist in static data",
 "System Date should be greater than Deal Date", /* ERR_DEALDT_LESSTHAN_SYSDATEA */
 "BCN Quantity is more",
 "BCN Price is not in band",
 "STT Amount is higher than specified limit", /*** End of BCN **/
 "Record already present for selected depository and security",/**TAKEOVER-AMISH**/
 "Quantity is greater then depository Quantity", /****MARKSHORTAGE ****/
 "Exchange code is Invalid",/*SQUARE OFF*/
 "Instrument Code is not authourized",
 "Client Code is not authourized",
 "Settlement Number is not Authourized.",/*SQUARE OFF ENDS */
 "In Exchange Order Upload, Instrument code is not authorized",
 "In Exchange Order Upload, Client code is not authorized",
 "In Exchange Order Upload, settlement number is not authorized",
 "In Exchange Order Upload, Deal date is a Holiday",
 "In Exchange Order Upload, market type is invalid",
 "In Exchange Order Upload, Scrip group is invalid",
 "Deal Information is missing",
 "Exchange Order Information is missing",
 "Exchange Order not in proper status ",
 "Deal not in proper status ",
 "Bucket already exists for given deal" ,
 "Address Length cannot be greater than 11",
 "Deal Date should be less than End Date",
 "Counter Pty data mismatched",
 "Exchange Code is not valid under NSCCL",
 "Exchange Code is not valid under BOISL",
 "Brokerage Amount is higher than specified limit",
 "Mapping  InterScheme details exist",
 "Mapping  Inter Scheme child details exist",
 "Party unauthorized",
 "Mapping Block Security child details exists",
 "Instrument code not authorized",  /* #define ERR_POOLACC_INSTRU_CD_NOT_AUTH 962 */
 "Settlement number not authorized",  /* #define ERR_POOLACC_SETT_NO_NOT_AUTH  964  */
 "Cannot Delete Format: In use",
 "SEBI Expiry Date is less than Deal Date",
 "RBI Expiry Date is less than Deal Date",
 "Exchange Code is NSE but Contract code does not contain 23",
 "Exchange Code is BSE but Contract code does not contain 01",
 "Exchange Code is NSE but Contract code does not contain 23",
 "Exchange Code is BSE But Contract code does not contain 01",
 "Client details exist",
 "Application Form Number exists",
 "Data mismatch between InterFII and Under Caution Flag",
 "Not enough positions. Short Sell trade found ",
 "Entitlement for attached event not Paid and Closed",
 "Pool Account Quantity is not equal to Total Allotted Quantity",
 "Max. Fee Adjustment in consolidated bill should be 'Y' or 'N'",
 "Max. Fee Adjustment in consolidated bill should be 'N' for sub accounts",
 "Max. Fee Adjustment only if holdings exist should be 'Y' or 'N'",
 "Money Settlement is pending ",
 "Security Settlement is pending ",
 "Instrument under no delivery",
 "Instrument under caution ",
 "Settlement Date greater than End Date",
 "Mutual Fund already exists for the selected Deal ",
 "PTC Principle Amount cannot exceed Nominal Value of Instrument",
 "Record already exist",
 "Auto-Authorization facility has already been enabled for the selected CRN ID",
 "Broker Code not Found",
 "You can Input for Self or Sub-Clients only",
 "Sub account can't be assigned Checker rights",
 "Select the authorizer who is having checker rights for the selected client code",
 "Deal Reference Number should not be more than 16 characters",
 "Transaction type is incorrect",
 "Exchange code is incorrect ",
 "Market type is incorrect",
 "Instrument Name is incorrect",
 "Broker Name is incorrect",
 "Failed to transfer deal",
 "Net Rate / Net Amount is not allowed for RF /DF Deals",
 "UnAuthorized Square-Off record exists ",
 "The Deal Reference No. is not for the selected client ", /* ERR_DLREFNO_NFND */
 "Date format should be DD/MM/YYYY", /*ERR_INCORRECT_DT_FRMT */
 "Obligation Details not defined for Master Account",
 "Obligation Details not defined for Group Account",
 "Master Account should have Obligation Level 'SELF'",
 "Billing Parameters not defined for Master Account",
 "Billing Parameters  not defined for Group Account",
 "Accounting Entries already generated", /*shailesh*/
 "Safekeep positions are becoming less than zero. Hence cannot proceed.", /* ERR_ZERO_POS */
"Payment for this service for selected billing period is already done",
"Pay amount Exceeds the bill amount",
"The mode of payment for this billing period is already selected as service-wise",
"The payment for this billing period is already done in total mode",
"The client set up OS amount not updated",
"The sum of authorized payments and unauthorized payments exceeds the Bill Amount for the selected billing date",
"Error :: PRO_GSSPLVAL.FIELD_VAL < Decimal len for Instrument", /* Added by Gouse - Decimal Length for MF- 01/10/2011 */
"No Application entries allowed as Cutover date for issue has passed", /* ERR_CUTOVER_DT_PASS */
"The Client Has Been Restricted To Purchase The Selected Instrument", /* added by shyam to restrict FII/NRI client from purchasing */
"Exchange Code is not MCS" , /*added by deependra for MCX enhancement */
"Settlement Calender cannot be modified as it's been used in a deal",	/*Priyanka - IB5881 CC calender changes*/
"Obligation Record Already Exists", /*Manasi- Obligation Recon*/
"State code exist but country code does not exist", /*Charuta MCX Phase 2 - Party Master Upload */
"City exist but country/state code does not exist", /* Charuta MCX Phase 2 - Party Master Upload  */
"CP code Length Cannot Be Greater Than 12",/*Priyanka -  Custodian Participant Master file upload*/
"Invalid state city or country code",/* Charuta Party Master */
"Depository code should be NSDL/CDSL", /*Added By Jeevan for Party Depository Mapping upload*/
"Exchgange code should be  NSE/BSE/MCS", /*Added By Jeevan for Party Depository Mapping upload*/
"Invalid Master Client Code",	/*Added by Vamshi for Party Client Mapping*/
"Pan Should be in Proper Format of ABCDE1234F", /*Added for ISKB_6285 - Validation for PAN (as per general nomenclature) & E-mail ID (with '@' sign and '.' Special character)*/
"Holder already exist for this client code", /*Added by Prateek on 28052014 for ISKB_198(FPI MAPPING)*/
"Customer id already mapped to the client", /*Added by Prateek on 28052014 for ISKB_198(FPI MAPPING)*/
"Single NSDL Group Id to be allocated to a Client",/* Added by Venkat on 18072014 for ISKB_198(FPI MAPPING)*/
"Cannot Upload.Account Is Not a Master Account Or Sub-account",/*ERR_PMS_MSTR_SUBACCT*/
"Sell Client And Buy Client Cannot Be Same.",/*ERR_PMS_CLIENT_INVALID 28072015 */
"Entitlement Generation is in progress; Please try after sometime", /*Retrofit by Kiran ISKB_7977- CA Server Down*/
"In Total mode Payment amount should be equal to Bill amount",
"Bill Amount is 0 for the given Bill Date and Service Code",
"Service Desc Length Cannot Be Greater Than 21", /*Retrofitted from IB1185 by Anjaneyulu for ISKB_1737 */
"Record cannot be deleted since bill is already generated for the Applicable From date",  /*Added by monica for ISKB_1737*/
"Uploaded Quantity Mismatches Original Quantity", /*added by aditya for for Global Pre-Match Extract*/
"Payment amount is greater than Bill amount", /*ISKB_1737 Billing Upload and Download*/ 
"Payment type should be either Total or Service", /*ISKB_1737 Billing Upload and Download*/
"Service quantity should be greater than 0", /*ISKB_1737 Billing Other Services Upload added by Pallavi*/
"Billing Period should not be future date", /*ISKB_1737 Billing Other Services Upload added by Pallavi*/
"Primary CPA and Secondary CPA should not be same",/*added by CHITRLEKHA for ADDITIONAL CLIENT DETAILS */
"Record Present in Tax Tracker;Deal Cannot be deleted", /*Added by shrinath for Tax Certificate ISKB_9306*/
"Payments cannot be done before Bill delivery", /* added by akshay for kotak_10958*/
"Settlement CCP is missing",	/*added by asmeet for kotak_12434*/
"Settlement CCP Market Type is missing",	/*added by asmeet for kotak_12434*/
"Settlement CCP - Settlement No is missing",	/*added by asmeet for kotak_12434*/
"DF or RF Client is not present or it's in freeze status",	/*added by asmeet for kotak_12434*/
"maximum 4 decimal allowed for Tax Rate",/*Changes done by Sunny for CS0020637*/
"Payment Event type is not CD", /*Changes done by Sunny for CS0020637*/
"Event With Priority 2 Is Already Exist", /* Added by Arunachalam CS0074500 -New Bilav file format changes --START    */
"Linked Event With Priority 1 Is Not Present",
"Post Ex-Date,Modification Is Not Allowed", 
"Issue Close date less than System date, hence cannot modify.", 
"Modify not allowed If Meeting Date less than System Date", 
"ISIN is not mapped with Instrument ",  /* CS0074500 -New Bilav file format changes --END    */
"Record has been modified by another program. Please try after sometime",
"Deal Reference Should Not Start With STKDIV,BONUS,CNV,CABBAL,CARTAL,CAIPAL,STKSPL",
"Bill amount for this client or cons_flag or service code not found",
"Record Not Found for given Client and Service Code", /* Added for Billing Client Upload */
"Record exists for given Client and Service Code",    /* Added for Billing Service Upload */
"Record Not Found for given Client and Service Code", /* Added for Billing Service Upload */
"Deal should be allowed only Off market for CSGL", /* CSGL enhancement by rahul */
"Deal code should be 3 and 4 for CSGL ", /* CSGL enhancement by rahul */
"Instrument sub type is not matched with CSGL ", /* CSGL enhancement by rahul */
"No Corp Id exists for provided Instrument Code, Client and Pay Date",
"Event Type should be either BI or RD",
"Deal date cannot be Greater than Surrender date",
"Deal date cannot be Greater than Restrict for Purchase date",
"Deal Date is Not between the Cooling Date and Disclosure Date",
"The instrument sub type is restricted for the client",
"SEBI Reg Date should not be in Future", /*Added For Data Patch by Kotubabu*/
"RBI  Reg Date should not be in Future", /*Added For Data Patch by Kotubabu*/
"Not a Valid Primary CPA", /*Added For Data Patch upload by Ram*/
"Not a Valid Secondary CPA", /*Added For Data Patch upload by Ram*/
"Not a Valid Fund Account Manager", /*Added For Data Patch upload by Ram*/
"Fatca Received should be either Y or N", /*Added For Data Patch upload by Ram*/
"Primary CPA is Mandatory if Secondary CPA provided", /*Added For Data Patch upload by Ram*/
"ISO Msg Format Value Should be S or Y", /*Added For Data Patch by Kotubabu*/
"Address should be either 8 or 11 characters", /*Added For Data Patch by Kotubabu*/
"DepoMap Client id value is Improper", /*Added For Data Patch by Kotubabu*/
"Invalid Client DepoId Value", /*Added For Data Patch by Kotubabu*/
"Invalid Message Type,for message num other than 3/31 message Type is S", /*Added For Data Patch by Kotubabu*/ 
"Deal Date is greater than Surrender/Restrict for Purchase Date", /* CHANGES DONE BY RAHUL */
"Deal Date is On or Less than the Cooling Of Date", /* Added by Anuradha.S for Company Level Limit Monitoring on 19/06/2024*/
"Deal Date is On or Less than the Reallign Due Date",  /* Added by Anuradha.S for Company Level Limit Monitoring on 20/06/2024*/
"Deal Date is Not between the Reallign Due Date and Disclosure Date", /* Added by Anuradha.S for Company Level Limit Monitoring on 20/06/2024*/
"Purchase/Sale are not allowed after the Surrender Due Date", /* Added by Anuradha.S for Company Level Limit Monitoring on 20/06/2024*/
"Deal Date is between the Disclosure Date and Surrender Due Date", /* Added by Anuradha.S for Company Level Limit Monitoring on 20/06/2024*/
"The instrument is restricted for the client", /* Added by Anuradha.S for Company Level Limit Monitoring on 18/07/2024*/
"Purchase Trades are not allowed during the Surrender period", /* Added by Anuradha.S for Company Level Limit Monitoring on 18/07/2024*/
"Script Code Should Be > 1 lakh Series", /* Added by rahul6 for T0*/
"Settlement Type should not be blank for on market deal",  /* Denish - T0 Setlement  */
"T0 Market type is not maintained in Instrument Exchange Details"    /* Denish - T0 Setlement  */
};

